### ISSUE TITLE
[Python] urllib2 returns HTTP Error 503: Service Temporarily Unavailable for yelp url

### ISSUE THREAD

**Issue by aishubalachandran** [Yelp/yelp-api#100]
Hi,
I generated the yelp api url by referring to the yelp-api code samples. It was working fine.
But suddenly, I have started getting Http 503 error on this line:
conn = urllib2.urlopen(signed_url) 
This returns HTTP Error 503: Service Temporarily Unavailable for any yelp.com url.

Please let me know what Im missing.

Thanks!

**Comment by watterso** [comment]
Hi @aishubalachandran can you post your code _without_ your credentials?
Also if you are using python you might find our client library helpful, find it here: [yelp-python](https://github.com/Yelp/yelp-python)

**Comment by aishubalachandran** [comment]
Hi,

Thanks for reaching back. I figured what the issue is:
So I think the IP of my remote box has been blocked by yelp. The API works fine in few other environments. Can you please help me in unblocking our IP address and tell me how to go about it?

Thanks!

**Comment by watterso** [comment]
Glad this is somewhat resolved, for this kind of issue please email api@yelp.com describing your issue and include the following information:
- Your _Consumer Key_ found at [yelp.com/developers/manage_api_keys](https://www.yelp.com/developers/manage_api_keys)
- The ip address you think is blocked.

**Comment by watterso** [comment]
I am going to go ahead and close this issue.
