### ISSUE TITLE
$response variable not working?

### ISSUE THREAD

**Issue by grhd76** [Yelp/yelp-api#101]
Greetings everyone! My background in programming is very limited. I have been trying to run the example PHP code but so far have been unsuccessful in retrieving any results. 

I'm using the XAMPP program to run the file locally. 
I have downloaded the oauth library, entered in all the api keys, and have left the original sample search terms in place.

When I run the file, I receive the error 
#!/usr/bin/php 
Notice: Trying to get property of non-object in C:\xampp\htdocs\yelpdatagithub.php on line 109
Notice: Trying to get property of non-object in C:\xampp\htdocs\yelpdatagithub.php on line 109
Notice: Trying to get property of non-object in C:\xampp\htdocs\yelpdatagithub.php on line 113
0 businesses found, querying business info for the top result "" Result for business "" found:

Lines 109 and 113 are:
  $business_id = $response->businesses[0]->id;
  count($response->businesses),

I'm assuming the errors are associated somehow with the $response or businesses variable. I left all the code as-is. Was there another step I'm missing? Thank you in advance for any help!

**Comment by mittonk** [comment]
Hm, PHP example works as expected on my PHP 5.3.2 Linux test setup.

Let me try Windows & XAMPP.

`var_dump($response)` might give us more info.

**Comment by mittonk** [comment]
Ah, https://www.apachefriends.org/index.html says XAMPP just released a PHP 7-based version.

@grhd76 : Could you do `php -v`?

**Comment by mittonk** [comment]
OK, reproduced problem with both:
* PHP 5.6 on XAMPP on Windows
* PHP 7.0.2 on XAMPP on Windows

So this is either a Linux-vs-Windows thing, or a 5.3 vs 5.6-and-later thing.

@virgytam , any suggestions?

**Comment by mittonk** [comment]
`var_dump($response)` gives `NULL`.  Digging into that.

**Comment by mittonk** [comment]
Signed URL is valid --- capturing that and curing it directly works.  So OAuth is working, and PHP curl is failing.

**Comment by mittonk** [comment]
http://stackoverflow.com/questions/8227909/curl-exec-always-returns-false

gives:
```
Fatal error: Curl failed with error #60: SSL certificate problem: unable to get
local issuer certificate in C:\Users\mittonk\pg\yelp-api-win\v2\php\sample.php o
n line 98
```

That's an error we can work with, excellent.

(The PHP example should probably give that level of diagnostics: filed #102.)

**Comment by mittonk** [comment]
OK, http://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate (in particular, the "XAMPP Server" answer)  did the trick.  I can now run the example code on Windows using XAMPP.

Now, to get this written up in a more coherent manner...
