### ISSUE TITLE
Search APIs failing on PostMan

### ISSUE THREAD

**Issue by RitwikChatterjee** [Yelp/yelp-api#104]
Hi,
I am trying to make Yelp Search API calls from PostMan and it is failing with the following error message. Please help.

```
{
  "error": {
    "text": "Signature was invalid",
    "id": "INVALID_SIGNATURE",
    "description": "Invalid signature. Expected signature base string: GET&https%3A%2F%2Fapi.yelp.com%2Fv2%2Fsearch&location%3DSan%2520Francisco%26oauth_consumer_key%3DXXXXXXGseOgew%26oauth_nonce%3DXXXX7zd%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1455655938%26oauth_token%3DXXXXXXePzEDSd%26oauth_version%3D1.0%26term%3Dfood"
  }
}
```

Here is how the request is being sent by PostMan:

`https://api.yelp.com/v2/search?term=food&location=San+Francisco&oauth_consumer_key=XXXXXXGseOgew&oauth_token=XXXXXXePzEDSd&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1455655938&oauth_nonce=Saq7zd&oauth_version=1.0&oauth_signature=ZD33Sbu8b1LGbwTQD9sQLYLS/so=
`

**Comment by mittonk** [comment]
@RitwikChatterjee : Are you using the OAuth 1.0a helper from https://www.getpostman.com/docs/helpers , or some other method to sign your request?

**Comment by RitwikChatterjee** [comment]
Yes, I am using the OAuth 1.0 helper on Postman.

**Comment by RitwikChatterjee** [comment]
Can someone please help me with this issue?

**Comment by mittonk** [comment]
Reproduced failure using Postman.  So, probably some non-obvious setting to find...

**Comment by mittonk** [comment]
@RitwikChatterjee : Looks like "Encode OAuth Signature" defaults to off in Postman; that should be turned on for Yelp.

Here's what worked for me:
1. Select "Authorization" => "OAuth 1.0".  Fill in the `oauth_consumer_key`, etc.
2. Click the checkbox for "Encode OAuth Signature".
3. Click "Update Request"
4. Click "Send"

**Comment by vasujain** [comment]
Even after Encode OAuth Signature i am getting "Signature was invalid", shall i create new issue with more details ?

**Comment by worrel** [comment]
To other who come here & still have issues I've found Postman is not replacing URL variables before generating the OAuth signature (e.g. if you have /business/:business-id) it will fail with invalid signature.  Otherwise the advice on #111 seems to work great.
