### ISSUE TITLE
Pre-requisites for "requirements.txt"?

### ISSUE THREAD

**Issue by jrs477** [Yelp/yelp-api#107]
I tried to follow your example on Github but have some very basic questions, coming from a novice background. 

I saved the file "requirements.txt" in a directory and then in the terminal tried to run:
`pip install -r requirements.txt`

The following message was returned: 
```
  Could not find a version that satisfies the requirement auth2==1.0 (from -r requirements.txt (line 1)) (from versions: )

No matching distribution found for auth2==1.0 (from -r requirements.txt (line 1))

```
What other basic steps would I need to take before running the "pip install" command?

Thanks very much for your help!

Kindly,

Jeremy

**Comment by mittonk** [comment]
Works as expected on my machine, so things are basically functional:
```
kmitton-laptop:~/pg/yelp-api/v2/python$ virtualenv venv
New python executable in venv/bin/python
Installing setuptools, pip...done.
kmitton-laptop:~/pg/yelp-api/v2/python$ source venv/bin/activate
(venv)kmitton-laptop:~/pg/yelp-api/v2/python$ pip install -r requirements.txt 
Downloading/unpacking oauth2==1.0 (from -r requirements.txt (line 1))
  Downloading oauth2-1.0.0.tar.gz
  Running setup.py (path:/Users/mittonk/pg/yelp-api/v2/python/venv/build/oauth2/setup.py) egg_info for package oauth2
    
Downloading/unpacking httplib2==0.9 (from -r requirements.txt (line 2))
...
```

@jrs477 , you saw `(from versions: )` --- could you please run `pip -vvv install oauth2==1.0` and paste the full output here?

Should start off something like:
```
(venv)kmitton-laptop:~/pg/yelp-api/v2/python$ pip -vvv install oauth2==1.0
Downloading/unpacking oauth2==1.0
  Getting page https://pypi.python.org/simple/oauth2/
  URLs to search for versions for oauth2==1.0:
  * https://pypi.python.org/simple/oauth2/1.0
  * https://pypi.python.org/simple/oauth2/
  Getting page https://pypi.python.org/simple/oauth2/1.0
  Could not fetch URL https://pypi.python.org/simple/oauth2/1.0: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/oauth2/1.0 when looking for download links for oauth2==1.0
  Analyzing links from page https://pypi.python.org/simple/oauth2/
    Found link https://pypi.python.org/packages/2.7/o/oauth2/oauth2-1.9rc1-py2-none-any.whl#md5=46c1705b59358f30f7456faae9205304 (from https://pypi.python.org/simple/oauth2/), version: 1.9rc1
    Found link https://pypi.python.org/packages/3.4/o/oauth2/oauth2-1.9.0.post1-py2.py3-none-any.whl#md5=3cea98a160f8825ea29bc3f3183e246f (from https://pypi.python.org/simple/oauth2/), version: 1.9.0.post1
...
```

**Comment by jrs477** [comment]
I ran the command you suggested. My terminal spat out a mess, ending with:

`InstallationError: Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/p6/qmn37h0j0lx_7cqd_z2qx59w0000gs/T/pip-build-oxJdCq/oauth2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/p6/qmn37h0j0lx_7cqd_z2qx59w0000gs/T/pip-i2GnUZ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/p6/qmn37h0j0lx_7cqd_z2qx59w0000gs/T/pip-build-oxJdCq/oauth2
`

**Comment by jrs477** [comment]
Learning more about oauth2, I see that it requires httplib2, which I tried to install. A similar error was returned when I tried `pip install httplib2`:

`Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/p6/qmn37h0j0lx_7cqd_z2qx59w0000gs/T/pip-build-hK2Zta/httplib2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/p6/qmn37h0j0lx_7cqd_z2qx59w0000gs/T/pip-0hRkNH-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/p6/qmn37h0j0lx_7cqd_z2qx59w0000gs/T/pip-build-hK2Zta/httplib2`

**Comment by jrs477** [comment]
Update: 
Everything worked after sudo-ing all installations :0

**Comment by mittonk** [comment]
Sudo's one approach --- glad that got you running.

I prefer using virtualenv:
* http://docs.python-guide.org/en/latest/dev/virtualenvs/

It lets me install Python packages in my own home directory (rather than needing sudo and installing them for everyone on the machine).  It also lets me keep one Python with all the packages for project A, and a different one with the packages for project B, without having to find versions that work for both A & B.

Glad you're on your way, I suspect the same steps will get yelp-python working!
