### ISSUE TITLE
Unpacking JSON output in sample.py

### ISSUE THREAD

**Issue by jrs477** [Yelp/yelp-api#108]
Hi,

What would be the most efficient way to access/index components within the JSON output from sample.py?

I am interested in using sample.py as base code for future calls to the Yelp API. Specifically, I'd like to run sample.py and at the end of the script write a new file (i.e., tab-delimited or csv) with select sections (i.e., long/lat coordinates, id, etc) of JSON output.

I figured I would create an empty list at the start of the script (i.e., `data = []`), and end the script with something like:

`  with open('yelp_output.txt', 'w') as f:`
`        f.write('example\n')`
`        f.write(repr(data))`

Any suggestions would be helpful, and apologies that this is a pretty basic question. Merci!

**Comment by dlgallagher** [comment]
There are definitely a lot of ways you can go with this, so definitely try experimenting to get the output & formatting you're looking for. 

sample.py's query_api() function first queries the search API endpoint, then queries the business API endpoint with the first business returned by search. The response from that is pretty printed to the console. 

In the query_api() function:
`response = search(term, location)`
and
`response = get_business(business_id)`
If you were to examine these 'response' variables while the code is running you'd see they are python dictionaries. If your goal is just to output one or both of these to a file (let me know if I'm misunderstanding) you can do it in several ways. 

The most straightforward is to just add to query_api() something like what you posted already:
```
str_to_write_to_file = "Here's a reponse! Get ready!\n" + repr(data)
with open('yelp_output.txt', 'w') as f:
    f.write(str_to_write_to_file)
```

`repr(response)` dumps the response dictionary to a string that looks just like it would in python. It's not particularly readable. You may instead want to use `json.dumps(response, ...<other kwargs>)` which has has optional kwargs you can pass in to sort the dictionary keys alphabetically, indent/pretty print, etc. (you can also json.dump directly to a file). 

If you wind up writing more code and get to the point where you're querying the business API endpoint for data on multiple businesses, it might be useful to start writing out a CSV file with a row per business for easier comparison. 

All of the above are general suggestions explained at a high level, but hopefully will give you some ideas.

**Comment by mittonk** [comment]
I'd also say:
* https://github.com/Yelp/yelp-python

is a much more full-featured Python interface, and might be easier to integrate into a larger codebase.

The Python example here is really just a demo to get you started, whereas the yelp-python clientlib is a client library.

**Comment by watterso** [comment]
Hi @jrs477 I second the suggestion to use our [python clientlib](https://github.com/Yelp/yelp-python)!
I made you a quick sample (see below) using the clientlib. Let me/us know if you have any more questions.

Code:
```python
import csv
import json

from yelp.client import Client
from yelp.oauth1_authenticator import Oauth1Authenticator

auth = Oauth1Authenticator(
    consumer_key='YOUR_KEY,
    consumer_secret='YOUR_SECRET',
    token='YOUR_TOKEN',
    token_secret='YOUR_TOKEN_SECRET'
    )

client = Client(auth)

businesses = client.search('San Francisco, CA', term='pizza').businesses

dicts_to_output = [
    {
        'name': biz.name,
        'id': biz.id,
        'top_category': biz.categories[0].alias if biz.categories else '',
        'rating': biz.rating,
        'review_count': biz.review_count
    }
    for biz in businesses
]

csv_keys = ['name', 'id', 'top_category', 'rating', 'review_count']
with open('my_output_file.csv', 'w') as output_file:
    dict_writer = csv.DictWriter(output_file, csv_keys, quoting=csv.QUOTE_NONNUMERIC)
    dict_writer.writeheader()
    dict_writer.writerows(dicts_to_output)
```
Sample of the output:
```csv
"name","id","top_category","rating","review_count"
"Tony's Pizza Napoletana","tonys-pizza-napoletana-san-francisco","pizza",4.0,2977
"Little Star Pizza","little-star-pizza-san-francisco","pizza",4.5,2491
"Golden Boy Pizza","golden-boy-pizza-san-francisco","pizza",4.5,2114
"Montesacro Pinseria-Enoteca","montesacro-pinseria-enoteca-san-francisco-5","pizza",4.5,172
....
```

**Comment by jrs477** [comment]
Thanks all for advice– very appreciated.

@watterso I ran your entire code, but there was a hangup in my terminal:
`AttributeError: 'list' object has no attribute 'rstrip'`

Then I ran the code line by line, and here's where I hit choppy waters:
`businesses = client.search('San Francisco, CA', term='pizza').businesses`

which returned

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/yelp/endpoint/search.py", line 44, in search
    self.client._make_request(SEARCH_PATH, url_params)
  File "/Library/Python/2.7/site-packages/yelp/client.py", line 47, in _make_request
    signed_url = self.authenticator.sign_request(url, url_params)
  File "/Library/Python/2.7/site-packages/yelp/oauth1_authenticator.py", line 34, in sign_request
    self.token
  File "/Library/Python/2.7/site-packages/oauth2/__init__.py", line 335, in sign_request
    self['oauth_signature'] = signature_method.sign(self, consumer, token)
  File "/Library/Python/2.7/site-packages/oauth2/__init__.py", line 649, in sign
    key, raw = self.signing_base(request, consumer, token)
  File "/Library/Python/2.7/site-packages/oauth2/__init__.py", line 641, in signing_base
    key = '%s&' % escape(consumer.secret)
  File "/Library/Python/2.7/site-packages/oauth2/__init__.py", line 63, in escape
    return urllib.quote(s, safe='~')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1301, in quote
    if not s.rstrip(safe):
AttributeError: 'list' object has no attribute 'rstrip'`

Any thoughts?

FYI, I pip installed yelp.

**Comment by jrs477** [comment]
@watterso and @mittonk 
Update: the issue causing the AttributeError was that I incorrectly called my key and token strings from a json object (ie., 'config_secret.json', per the Yelp python clientlib example). However, when I cut and paste my consumer_secret, consumer_key, token, and token_secret directly into the code you recommended, I then get the following error:

```
Traceback (most recent call last):
  File "yelp_api.py", line 26, in <module>
    businesses = client.search('San Francisco, CA', term='pizza').businesses
  File "/Library/Python/2.7/site-packages/yelp/endpoint/search.py", line 44, in search
    self.client._make_request(SEARCH_PATH, url_params)
  File "/Library/Python/2.7/site-packages/yelp/client.py", line 48, in _make_request
    return self._make_connection(signed_url)
  File "/Library/Python/2.7/site-packages/yelp/client.py", line 54, in _make_connection
    self._error_handler.raise_error(error)
  File "/Library/Python/2.7/site-packages/yelp/errors.py", line 99, in raise_error
    response
yelp.errors.InvalidSignature
```

I know this means that my oauth_signature is invalid, but I am totally stumped, given that I am entering my correct API keys/secrets/token verbatim. Any tips to make this work?

**Comment by watterso** [comment]
Hey @jrs477,
First off, regarding loading keys from file, not sure exactly what issues you were having, but below is how I do it. I'm unsure of your level of python so I'll over-explain:
* `json.load()` loads the contents of a file object (containing JSON) into a python dictionary
* the `**creds` shorthand expands a dictionary into 'kwargs', short info on that [here](http://stackoverflow.com/questions/1769403/understanding-kwargs-in-python), more verbose explanation in the [official python docs](https://docs.python.org/2/tutorial/controlflow.html#keyword-arguments).
snippet from app.py:
```python
import json
...
from yelp.oauth1_authenticator import Oauth1Authenticator
...
with open('keys.json') as creds_file:
    creds = json.load(creds_file)
auth = Oauth1Authenticator(**creds)
```
(redacted) contents of keys.json:
```json
{
    "consumer_key": "REDACTED",
    "consumer_secret": "REDACTED",
    "token": "REDACTED",
    "token_secret": "REDACTED"
}
```
Regarding `yelp.errors.InvalidSignature`:
Assuming that your credentials are correct, this could happen if there is a large amount of time between the signing of a url and it hitting our server. This is the case because the signature is based on the timestamp and if the server receives a signed response that is too far in the past, it returns that it is invalid. Could this me the case?

**Comment by watterso** [comment]
@jrs477 hows it going? Are you still experiencing this error?

**Comment by jrs477** [comment]
@watterso thanks for the explanation. Yes, `yelp.errors.InvalidSignature` is resolved.

I now have another error popping up ("TypeError: character mapping must return integer, None or unicode" when the compiler hits `businesses = client.search('San Francisco, CA', term='pizza').businesses`).

But that's another can of worms...

Thanks again!

**Comment by watterso** [comment]
Glad to hear! If you can't resolve that issue, feel free to open another issue

**Comment by jrs477** [comment]
To the folks who helped me troubleshoot, here's a product of my [tinkering](https://jschwartzbord.shinyapps.io/fr_wine/).

**Comment by tomelm** [comment]
@jrs477 that's pretty cool, thanks for sharing!

**Comment by watterso** [comment]
Cool stuff! There is also the `cheese` category for fromageries if you want to add this data for your cheese post :wink: 

PS: I spent a semester abroad in Montpellier, enjoy your time there :smile:
