### ISSUE TITLE
Search APIs failing on PostMan

### ISSUE THREAD

**Issue by vasujain** [Yelp/yelp-api#111]
Duplicate of #104 . Solution proposed there did not worked. 

{
  "error": {
    "text": "Signature was invalid",
    "id": "INVALID_SIGNATURE",
    "description": "Invalid signature. Expected signature base string: GET&https%3A%2F%2Fapi.yelp.com%2Fv2%2Fsearch&location%3DSan%2520Francisco%26oauth_consumer_key%3D**XXX**%26oauth_nonce%3DzZLlOk%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1456811672%26oauth_token%3D**XXX**%26oauth_version%3D1.0%26term%3Dfood"
  }
}

Here is how the request is being sent by PostMan:
https://api.yelp.com/v2/search?term=food&location=San+Francisco&oauth_consumer_key=XXX&oauth_token=XXX&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1456811672&oauth_nonce=zZLlOk&oauth_version=1.0&oauth_signature=1bHvZ4yFX6h5PzjdrJqhx11S%2FcA%3D

**Comment by vasujain** [comment]
@mittonk can you help me with this ?

**Comment by watterso** [comment]
Hey there @vasujain!
I followed steps from #104 and was able to reproduce your error. What ended being my issue was that something somehow got into the Headers tab to the right of Authorization (see below). I went into there and cleared headers out (one of them was oauth related) and that fixed it.
![screen shot 2016-03-01 at 10 23 12 am](https://cloud.githubusercontent.com/assets/1614083/13437227/f93e6130-df97-11e5-8e41-4fe788db4ada.png)

**Comment by vasujain** [comment]
@watterso Header tab seems to be empty already for me. Pls see screenshot. 
![screenshot 2016-03-01 15 32 28](https://cloud.githubusercontent.com/assets/1364787/13445733/e2e59928-dfc2-11e5-8b90-f4ad9adff644.png)

**Comment by watterso** [comment]
Cutting it close there with exposing your api keys! :laughing:  
Other possibilities:
* Can't tell from screenshot, but make sure you signature method is 'HMAC-SHA1'
* Make sure to click the update request button, in case the timestamp and nonce don't automatically update, the request is only valid for a short amount of time.
* (probably should've been the first question) Double check you api keys on the website.

**Comment by vasujain** [comment]
You bet. Just enough crop to avoid exposure. :) 

- signature method is 'HMAC-SHA1'
- Make sure to click the update request button, in case the timestamp and nonce don't automatically update, the request is only valid for a short amount of time.    **--- Already Done**
- (probably should've been the first question) Double check you api keys   **--- Cross checked. **

Do you have any postman collection which i can use ? may be you can create one and i may try that ?

**Comment by watterso** [comment]
I'm a total noob at postman but I tried my best, just fill in your keys :)

(i had to zip to make github let me attach)
[yelp_public_api_v2_search_example.zip](https://github.com/Yelp/yelp-api/files/159595/yelp_public_api_v2_search_example.zip)

**Comment by vasujain** [comment]
That didnt helped either. Getting the same issue "Invalid signature. Expected signature base string" . Does the cf-ray id helps for the request i made ? cf-ray →280a4415def2288e-SJC

**Comment by watterso** [comment]
I figured it out, with your cf-ray I took a look at our logs, looks like all your requests have the same Oauth_signature and nonce, these should change from request to request as the request is signed with a new timestamp/nonce. I'm not familiar enough with postman to make sure nonce (and therefore signature) are updated with the new timestamp. When I click Send or Update Request those values are updated.

Maybe try clearing all your parameters, adding back the term and location parameters then adding oauth again in an effort to reset postman?

**Comment by vasujain** [comment]
Sure. Will try that as well. THanks

**Comment by watterso** [comment]
@vasujain is this still an issue?

**Comment by vasujain** [comment]
'Yep, it worked. The trick was to auto generate timestamp and nonce. Select oauth1.0 in postman, fill up all the params, clear timestamp and nonce and update request.

**Comment by watterso** [comment]
Awesome :smile:
