### ISSUE TITLE
Can't find a specific place using API

### ISSUE THREAD

**Issue by danielcovill** [Yelp/yelp-api#115]
I'm searching for parks within 1000m of a point using the following query: 

https://api.yelp.com/v2/search/?ll=39.7291624,-104.9874124&radius_filter=1000&category_filter=parks&limit=5

There's a park named "Sunken Garden Park" that should show up in the results but for some reason doesn't. How can I or should I report the issue?

https://www.yelp.com/biz/sunken-gardens-park-denver

**Comment by mittonk** [comment]
The search API doesn't return reviews with 0 businesses in some places, including this one.

Sounds like we need to:
1. At least document the restriction.
2. Consider relaxing it.

**Comment by danielcovill** [comment]
Reviews with 0 business, or business with 0 reviews? Not trying to be pedantic, just making sure I understand.

Thanks for the fast response!

**Comment by mittonk** [comment]
OK, I clearly need more caffeine.  You're absolutely right, businesses with 0 reviews.

**Comment by watterso** [comment]
This issue was also picked up in #112 we should document this

**Comment by mittonk** [comment]
Need to specify that only "recommended" reviews count towards this requirement, see not-recommended case in #120 .

**Comment by watterso** [comment]
Closing...
**Resolution:** Search API does not return results that have 0 recommended reviews. Plain old reviews are a superset of recommended views, so having 0 reviews means 0 recommended reviews.
