### ISSUE TITLE
Search API not returning a specific business despite having reviews

### ISSUE THREAD

**Issue by bizmate** [Yelp/yelp-api#120]
When searching for 'Affordable Plumbing, Rooter and Water Heaters' in 'Scottsdale', I would expect to see http://www.yelp.com/biz/affordable-plumbing-rooter-and-water-heaters-scottsdale-2 but this is not returned at the moment.

Any clue on what is going wrong?

**Comment by mittonk** [comment]
@bizmate : Looks like all three reviews on
* https://www.yelp.com/biz/affordable-plumbing-rooter-and-water-heaters-scottsdale-2

are "not-recommended."

Clarifying #115 to say "must have recommended reviews", that's indeed what we're hitting here.  Sorry!
