### ISSUE TITLE
cannot get any actionlinks

### ISSUE THREAD

**Issue by daveymuso** [Yelp/yelp-api#121]
I've tried always and cannot get any extra data - I have these lines which mimic the other url vars

$DEFAULT_ACTIONLINKS = 'True';

$url_params['actionlinks'] = $GLOBALS['DEFAULT_ACTIONLINKS'];

**Comment by mittonk** [comment]
At a high level: The URL request is what matters.  

1. We can debug the PHP / Python / Java / whatever by seeing what api.yelp.com/... URL it generates.
2. We can debug that URL by forming a similar request using https://www.yelp.com/developers/api_console .

@daveymuso : What business or search are you using?  Not all businesses have extra action links, so it matters.

**Comment by mittonk** [comment]
From the API side,
`https://api.yelp.com/v2/search?location=San Francisco, CA&actionlinks=true` shows `eat24_url` on business `the-flying-falafel-san-francisco-3` (but not most of the other search results).

Let's see what URL your code generates...

**Comment by mittonk** [comment]
OK, your code does indeed find the Flying Falafel's Eat24 link when searching for "" in "San Francisco, CA".

Not every business has actionlinks; if you find a business or search that you think should, but doesn't show in the API, please post it here and I'll help dig in.

**Comment by daveymuso** [comment]
thanks. I investigated further and it was due to not actually getting any results with deals on :) Got is sorted

**Comment by mittonk** [comment]
Sounds good!
