### ISSUE TITLE
Invalid parameter term

### ISSUE THREAD

**Issue by martap-telenav** [Yelp/yelp-api#124]
Hi all,

I am trying to make a request with a term containing only some special characters (term=ș or term=Гомель).
For these requests I get a response   {... "id": "INVALID_PARAMETER", "field": "term" ...}

The sent urls are:
http://api.yelp.com/v2/search?ll=48.13912%2C11.5726&radius_filter=40000.0&offset=0&limit=10&term=%C8%99&sort=0

http://api.yelp.com/v2/search?ll=48.13912%2C11.5726&radius_filter=40000.0&offset=0&limit=10&term=%D0%93%D0%BE%D0%BC%D0%B5%D0%BB%D1%8C&sort=0

If I add let's say the 'a' character (term=aș or term=aГомель) the result is ok.

The sent urls are in this case:
http://api.yelp.com/v2/search?ll=48.13912%2C11.5726&radius_filter=40000.0&offset=0&limit=10&term=a%C8%99&sort=0

http://api.yelp.com/v2/search?ll=48.13912%2C11.5726&radius_filter=40000.0&offset=0&limit=10&term=a%D0%93%D0%BE%D0%BC%D0%B5%D0%BB%D1%8C&sort=0

Is this a known issue, the term has limitations or I am doing something wrong?

Thanks.

**Comment by mittonk** [comment]
Hm, I've got a few ideas --- we don't have Romanian reviews or businesses yet, so I wonder if we're stripping out those characters; this would leave `term=` (maybe an error) or `term=a` (valid query, unhelpful results).

@martap-telenav , are you using one of the API examples (PHP, node.js, etc) or something else?

**Comment by mittonk** [comment]
(https://www.yelp.com/developers/api_console gives a different an unrelated failure on `ș`, that's likely a different bug in the web console.
```
{
    "error": {
        "text": "Signature was invalid", 
        "id": "INVALID_SIGNATURE", 
        "description": "Invalid signature. Expected signature base string: GET&https%3A%2F%2Fapi.yelp.com%2Fv2%2Fsearch%2F&location%3DSan%2520Francisco%252C%2520CA%26oauth_consumer_key%3DsWc_ig2aihT0s-6Yf-zGIQ%26oauth_nonce%3D75295481%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1461683746..."
    }
}
```
)

**Comment by mittonk** [comment]
Repro'd using yelp-python clientlib (and found another Unicode issue https://github.com/Yelp/yelp-python/issues/46 on the way).

OK, digging in.

**Comment by mittonk** [comment]
Looks like the issue's server-side, rather than client-encoding-side.

**Comment by martap-telenav** [comment]
@mittonk I am using java (scribe lib)

**Comment by mittonk** [comment]
Need to pin down and fix backend issue.

**Comment by mittonk** [comment]
Need to reboot this investigation.

**Comment by mittonk** [comment]
Repro'd again using Postman, poking more.

**Comment by mittonk** [comment]
Looks like this is specific to languages that Yelp doesn't yet support --- there's no Yelp Romania yet.

As a workaround, I'd suggest searching in some of the languages Yelp supports:
* https://www.yelp.com/developers/documentation/v3/supported_locales

(That list is from the newer Fusion documentation, but the V2 list of locales is the same.)

**Comment by mittonk** [comment]
Also: www.yelp.com shows the same behavior, this isn't API-specific.
* https://www.yelp.com/search?find_desc=%C8%99&find_loc=sf => "Sorry, that's an invalid search term."
* https://www.yelp.com/search?find_desc=pizza%C8%99&find_loc=sf => "pizza" results.

Based on that, closing issue.
