### ISSUE TITLE
Newbie!  Code to show Yelp Reviews on My Webpage

### ISSUE THREAD

**Issue by Funmommie** [Yelp/yelp-api#125]
Hello, Everyone!  I am a business owner (I teach piano lessons) and an extreme novice at coding.  I was hoping to put a dynamic view of my yelp reviews on my webpage.  Is this possible?  I know about the button the yelp supplies that sends my users to yelp, but am hoping to have something directly integrated into my site.  I am hoping for html code that I could copy and paste into a widget.  I do apologize for any incorrectly-used terminology in this post!  Thank you very much for any help you can give.

**Comment by mittonk** [comment]
@Funmommie : The API is meant for people writing code; if you'd like a ready-to-use widget, I'd start with https://www.yelp.com/bling .
