### ISSUE TITLE
geo_accuracy field in Location?

### ISSUE THREAD

**Issue by alickrxu** [Yelp/yelp-api#127]
Quick question: I was wondering the the `location.geo_accuracy` field means. I couldn't find anything in the documentation talking about it.

Here is an example of what I'm talking about. When I run a business search the response includes this (`geo_accuracy` is right below `display_address`):
```
"location": {
        "city": "Isla Vista", 
        "display_address": [
            "879 Embarcadero Del Norte", 
            "Isla Vista, CA 93117"
        ], 
        "geo_accuracy": 8.0, 
        "postal_code": "93117", 
        "country_code": "US", 
        "address": [
            "879 Embarcadero Del Norte"
        ], 
        "coordinate": {
            "latitude": 34.4133, 
            "longitude": -119.85569
        }, 
        "state_code": "CA"
    }
```

**Comment by mittonk** [comment]
You're right, we don't have any documentation for this.

Short answer: It's a combination of how confident we are in the lat-lng coordinate data, and how large an area it represents.  If we have a street address for a specific building (common in business results), it's 8.0; if we only found a general neighborhood (like the coordinates for "Downtown, Some City") it's 4.5.

On www.yelp.com, this number is used to determine whether we show regular map markers or the question-mark-we're-not-entirely-sure-where-this-business-is markers for businesses.

We should probably write up a list and explain some of the factors that go into this number.

**Comment by chester-thomas** [comment]
I think it's how close the returned place is to your search criteria. I find its accuracy rating increases when I use longitude and latitude up to as much as 9.5 for places close to where I am standing.

You can thus use it to sort results, in my app it means the places are sorted by how close to you they are.

**Comment by mittonk** [comment]
I'd use "distance" for how far things are from the search location.

"geo_accuracy" is about the precision of the location, not how far it is.

**Comment by watterso** [comment]
Closing, see this section from @mittonk's response for the answer:
> Short answer: It's a combination of how confident we are in the lat-lng coordinate data, and how large an area it represents. If we have a street address for a specific building (common in business results), it's 8.0; if we only found a general neighborhood (like the coordinates for "Downtown, Some City") it's 4.5.
