### ISSUE TITLE
Malformed JSON

### ISSUE THREAD

**Issue by chester-thomas** [Yelp/yelp-api#128]
I am using php codeigniter and I can successfully generate a response. However the response contains string at the beginning and does not parse through correctly as a result:

`string(15566) "{"region": {"span": {"latitude_delta": 0.08290248999999505, "longitude_delta": 0.1358963099999997}, "center": {"latitude": 52.54999135, "longitude": -2.06822835}}, "total": 40, "businesses": [{"is_claimed": true, "rating": 4.5, "mobile_url": "http://m.yelp.com/biz/grand-theatre-wolverhampton?utm_campaign=yelp_api\u0026utm_medium=api_v2_search\u0026utm_source=ZKJ8ayqrUgA4QIOxhy_vYA", "rating_img_url": "https://s3-media2.fl.yelpcdn.com/assets/2/www/img/99493c12711e/ico/stars/v1/stars_4_half.png", "review_count": 14, "name": "Grand Theatre", "rating_img_url_small": "https://s3-media2.fl.yelpcdn.com/assets/2/www/img/a5221e66bc70/ico/stars/v1/stars_small_4_half.png", "url": "http://www.yelp.com/biz/grand-theatre-wolverhampton?utm_campaign=yelp_api\u0026utm_medium=api_v2_search\u0026utm_source=ZKJ8ayqrUgA4QIOxhy_vYA", "categories": [["Performing Arts", "theater"], ["Music Venues", "musicvenues"]], "phone": "+441902429212", "snippet_text": "I have very fond memories of the grand theatre. Every christmas we would go to see whatever was showing and there was always a great atmosphere. Inside it...", "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/3MmL4rcuWjCbA4POlEhkJw/ms.jpg", "snippet_image_url": "http://s3-`

**Comment by mittonk** [comment]
Hm, sounds like we need to find a "parse as JSON" option in CodeIgniter.  Yelp API responses are JSON.

http://stackoverflow.com/questions/19027205/get-json-response-in-codeigniter  sounds pretty similar.  Perhaps try `json_decode()` like in that discussion?

**Comment by mittonk** [comment]
For an example, check out where the PHP example code calls `json_decode()`:
* https://github.com/Yelp/yelp-api/blob/master/v2/php/sample.php#L137

**Comment by chester-thomas** [comment]
Many thanks, it indeed was the issue. I added json_decode($data) and it resolved my issue.

**Comment by mittonk** [comment]
Excellent.
