### ISSUE TITLE
Invalid Signature

### ISSUE THREAD

**Issue by mj62** [Yelp/yelp-api#129]
Hi, just getting started on this. 

Looking to run GET `https://api.yelp.com/v2/search?category_filter=Nightlife&location=Los+Angeles&limit=1`

I've filled out the proper Consumer/Token Key/Secret. 

In Headers I have 
Authorization: `OAuth oauth_consumer_key="z-0YvGnBFXDH8bfp8MOjqQ",oauth_token="b2tBzAGfqRZtk7G-3qlvPo71keUbsr1V",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1462904865",oauth_nonce="0ikkG5",oauth_version="1.0",oauth_signature="0X2ochAbY%252Fcba4vNB4cWXDO%252BLYo%253D"`

Getting back
`{
  "error": {
    "text": "Signature was invalid",
    "id": "INVALID_SIGNATURE",
    "description": "Invalid signature. Expected signature base string: GET&https%3A%2F%2Fapi.yelp.com%2Fv2%2Fsearch&category_filter%3DNightlife%26limit%3D1%26location%3DLos%2520Angeles%26oauth_consumer_key%3Dz-0YvGnBFXDH8bfp8MOjqQ%26oauth_nonce%3D0ikkG5%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1462904865%26oauth_token%3Db2tBzAGfqRZtk7G-3qlvPo71keUbsr1V%26oauth_version%3D1.0"
  }
}`

Is there something I'm not doing correctly here?

**Comment by uclamapshare** [comment]
I'm having the exact same issue!! =( Anyone else can solve?

**Comment by albertkun** [comment]
I'm having the exact same issue!! =( Anyone else can solve?

**Comment by mj62** [comment]
Taking all filters and headers out and starting over and checking the 3 of the 4 options seemed to make it work. Make sure you press update right before you send.

**Comment by mittonk** [comment]
@mj62 : "press update" sounds like Postman, is that what you're using?

**Comment by mj62** [comment]
@mittonk Yes, sorry I forgot to specify that in original post.
