### ISSUE TITLE
Yelp Listing Industry Classification to NAICS code mapping/cross walk/Concordance? 

### ISSUE THREAD

**Issue by TimbW** [Yelp/yelp-api#131]
Hey folks
For available yelp listing industry categories, is there a cross walk to NAICS codes?
Any help appreciated!

**Comment by mittonk** [comment]
Hm, not yet.  What's your use case?

**Comment by TimbW** [comment]
Connecting business software that requires NAICS codes, want to map to
listing categories on yelp. for B2B.
Cheers
Tim

**Comment by mittonk** [comment]
Sorry, we don't have a mapping --- you'd need to write your own based on the category list at
* https://www.yelp.com/developers/documentation/v2/all_category_list

Good luck!

**Comment by daxiang28** [comment]
@TimbW did you ever figure out a mapping for NAICS?
