### ISSUE TITLE
Yelp "loc" XML feeds gone?

### ISSUE THREAD

**Issue by jeffehobbs** [Yelp/yelp-api#132]
For years I have very much enjoyed browsing recent reviews via the location-based XML feeds, ala:

https://www.yelp.com/syndicate/area/rss.xml?loc=Northampton%2C+MA

Seems like they have stopped being updated a short while ago? Is there any way to bring them back or mimic this functionality (geofenced location + recency of review) with the API?

Thanks!

**Comment by tomelm** [comment]
Hey @jeffehobbs! The API does not provide functionality to mimic those RSS feeds.
