### ISSUE TITLE
Historic data from Yelp API

### ISSUE THREAD

**Issue by zxy1219** [Yelp/yelp-api#134]
Dear all,

Is it possible to get historic data from the Yelp API? For example, I want to compare the numbers of fast food restaurants between now and 10 years ago, how to set up the searching strategy?

Thanks!

Sue-ying

**Comment by mittonk** [comment]
The Yelp API doesn't yet have this sort of date filtering.

(In addition, Yelp was much smaller in 2006 --- even if we could do that query, you might see a lot of "yelp was smaller" effects rather than "there were fewer fast food places")
