### ISSUE TITLE
API Help

### ISSUE THREAD

**Issue by creationburst** [Yelp/yelp-api#138]
We're currently trying to explore a user case for an app and I'm unsure if its possible based off what I've seen in the API. What we'd like to do is pull photos on an item based level along with the tagged description. So say someone uploaded a photo of the club sandwich at a restaurant we'd like to pull that Yelp photo along with what was tagged with it. User case being someone is at a restaurant and wants to quickly see the items on a food menu but wants to visually see what this food looks like as most menus are text based. 

I also looked into the Locu API, but again doesn't look like this is possible. 

If anyone has any thoughts on how to help I would greatly appreciate it! Perhaps there are other APIs such as Google Images or FourSquare that could help.

**Comment by virgytam** [comment]
Hi creationburst, currently the API only returns 1 photo per business, so there isn't a way to retrieve specific photos or get more than 1 photo.

**Comment by creationburst** [comment]
Hey thanks for the comment. That was my understanding as well. Any ideas for how this could possibly be done. I'm looking into Locu, Google's APIs, and FourSquare at the moment. I'm hoping there is a way.

**Comment by watterso** [comment]
@creationburst doesn't seem like a simple problem to solve and this is now out of the scope of our api, going to close this.
