### ISSUE TITLE
Category list missmatch

### ISSUE THREAD

**Issue by tushtush** [Yelp/yelp-api#14]
Hello,
How come the category lists provided do not match those on site? (http://www.yelp.com/developers/documentation/category_list)

For example "Gelato" is in the webpage but not in any of the lists...

**Comment by mittonk** [comment]
My plan is to remove this directory and supply a direct link to the JSON dump on that page. (That download URL is still in some flux).

(I also half-remember this being a code dependency for something, tracking that down.)

**Comment by mittonk** [comment]
OK, there's now a nice downloadable JSON file at
* https://www.yelp.com/developers/documentation/v2/all_category_list/categories.json

We no longer need local copies, removing them.
