### ISSUE TITLE
CocoaPod shows error when doing pod install

### ISSUE THREAD

**Issue by WadeSellers** [Yelp/yelp-api#140]
I am attempting to install YelpAPI to a Swift app but I am getting an error in Terminal and I cannot find documentation to solve the issue.

The error I receive when I pod install is:

[!] The platform of the target `ForTheTroops` (iOS 9.3) is not compatible with `YelpAPI (1.0.3)`, which does not support `iOS`.

and this is my Podfile setup going off the directions from your CocoaPod install instructions:

source 'https://github.com/CocoaPods/Specs.git'

target 'ForTheTroops' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ForTheTroops

    pod 'AFNetworking', '~> 3.0'
    pod 'YelpAPI', '~> 1.0'

  target 'ForTheTroopsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ForTheTroopsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

Any help would be really appreciated here. Thank you!

**Comment by benasher44** [comment]
Hi @WadeSellers! Can you try something for me? I think there might be something up with our podspec. Here's an updated version:
```
Pod::Spec.new do |s|
  s.name             = "YelpAPI"
  s.version          = "1.0.3"
  s.summary          = "Objective-C client library for accessing the Yelp Public API."

  s.description      = <<-DESC
			This pod is designed to help developers using both Objective-C 
			and Swift in accessing the Yelp Public API. A thorough
			readme with usage examples can be found at https://github.com/Yelp/yelp-ios.
                       DESC

  s.homepage         = "https://github.com/Yelp/yelp-ios"
  s.license          = 'MIT'
  s.author           = 'Yelp'
  s.source           = { :git => "https://github.com/Yelp/yelp-ios.git", :tag => s.version.to_s }

  s.ios.deployment_target     = '7.0'
  s.osx.deployment_target     = '10.9'
  s.requires_arc = true

  s.source_files = "Classes/**/*.{h,m}"
  s.private_header_files = 'Classes/**/*Private.h'

  s.dependency 'TDOAuth', '~> 1.1'
end
```

Can you paste that into a file locally called `YelpAPI.podspec`? Then in your Podfile, make your pod line look like this:

`pod 'YelpAPI',  :podspec => 'path_to_yelpapi.podspec'`

If this works out for you, we'll publish an updated podspec

**Comment by WadeSellers** [comment]
I followed the instruction above. I created the YelpAPI.podspec file, pasted everything into it. I placed the .Podspec file right into the app where the .xcodeproj file is located too.  I added the line to the Podfile, ran pod install, and it looks like it can't locate the .Podspec file from what I read in the terminal response. 

Let me know if I can help anymore please.

![error from pod install](https://cloud.githubusercontent.com/assets/7055351/16242986/5d96547c-37b2-11e6-83ff-7a40e8886d93.png)

**Comment by WadeSellers** [comment]
I also have tried moving the .Podspec file into the Pods/Local Podspecs folder as well but no difference when trying Pod Install

**Comment by WadeSellers** [comment]
I'm not sure I understand. Where did I assign it twice?

**Comment by benasher44** [comment]
@WadeSellers it's all fixed fixed now. Go ahead and put your Podfile back to how it was before and run `pod install --repo-update`. The "assign twice" refers to a bug on our end. You didn't do anything :)

**Comment by benasher44** [comment]
If it's already installed, you may need to run `pod update YelpAPI `

**Comment by WadeSellers** [comment]
HEY-O!!!! Now we're cooking with fire!  Worked perfectly.  Thanks so much for looking into this and solving the issue. I really didn't want to use Google Place API if I didn't have to. Yelp has all the info I need and more for my project so I was really looking forward to utilizing it... and now I can!  

You're awesome!  Thanks again!

-Wade
