### ISSUE TITLE
How to get business open hours info from business id

### ISSUE THREAD

**Issue by sanjukhunt** [Yelp/yelp-api#143]
I want to show how many hours business open. I have tried but i am unable to get the those info from business id.

**Comment by tomelm** [comment]
Hi @sanjukhunt, we don't currently provide this in the API

**Comment by doriansgithub** [comment]
So how does Apple get it?

**Comment by tomelm** [comment]
This is now on the Fusion API if you want it: https://www.yelp.com/developers/documentation/v3/business

**Comment by doriansgithub** [comment]
Thanks, we’ll check it out!
