### ISSUE TITLE
Yelp API is failing in Postman

### ISSUE THREAD

**Issue by prsmax** [Yelp/yelp-api#145]
{
    "error": {
        "text": "Signature was invalid",
        "id": "INVALID_SIGNATURE",
        "description": "Invalid signature. Expected signature base string: GET&https%3A%2F%2Fapi.yelp.com%2Fv2%2Fsearch&location%3DSan%2520Francisco%26oauth_consumer_key%3DHJ0FdPSYP0GlbIAKq-Wdcw%26oauth_nonce%3DKyv7x3%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1467023743%26oauth_token%3DpO9EzdIt_C8z5obGMmqtFJ9mFepDA8vE%26oauth_version%3D1.0%26term%3Dfood"
    }
}

http://my.jetscreenshot.com/demo/20160627-8rjq-18kb.jpg
http://my.jetscreenshot.com/demo/20160627-f1i0-32kb.jpg

Also i try to clear timestamp, Nonce and oauth_signature  - PostMan generate it, but i have the same error

**Comment by butterfield** [comment]
Hi prsmax,

Your screenshots have expired :( Are you still having this problem? If so, can you give me some more info about how you made your request? (Maybe this was in your screenshots.)

**Comment by mittonk** [comment]
"%2520" looks double-escaped to me.

How are you entering the location?

Does location "Boston" (no spaces) work?

Again, the answers may have been in your screenshots, but they've expired.
