### ISSUE TITLE
INVALID_SIGNATURE

### ISSUE THREAD

**Issue by simonnarang** [Yelp/yelp-api#146]
Hi there,

I am having trouble using the search API.

I am creating a signature from a percent-encoded base string and signing it with `<consumer secret>&<token secret>`

Here is my Printed Base Signature:
`https%3A%2F%2Fapi.yelp.com%2Fv2%2Fsearch%3Flimit%3D20%26location%3DBerlin%26oauth_consumer_key%3DT8p3rlxD_eQLz6Jl7ePghw%26oauth_nonce%3D60b30afc5087fcc509eb4245d1e9410c%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1466993825%26oauth_token%3DdQQHrPIkT9piZc95zwOuCBwav3ICMp9e%26oauth_version%3D1.0%26term%3Dbar`

When I run the code, the API gives me the error
`("{\"error\": {\"text\": \"Signature was invalid\", \"id\": \"INVALID_SIGNATURE\", \"description\": \"Invalid signature. Expected signature base string: GET\\u0026https%3A%2F%2Fapi.yelp.com%2Fv2%2Fsearch\\u0026limit%3D20%26location%3DBerlin%26oauth_consumer_key%3DT8p3rlxD_eQLz6Jl7ePghw%26oauth_nonce%3D60b30afc5087fcc509eb4245d1e9410c%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1466993825%26oauth_token%3DdQQHrPIkT9piZc95zwOuCBwav3ICMp9e%26oauth_version%3D1.0%26term%3Dbar\"}}")`

I am having trouble understanding this error as OAuth1.0 spec says that the beginning of the base string should be `GET&` not `GET\\`.

Thanks,

Simon

**Comment by butterfield** [comment]
Hey Simon,

First, you're seeing \\u0026 because the response string represents characters like the & symbol as a unicode escape sequence. \u0026 represents &, and the first \ escapes the second \ so the second \ doesn't escape the u.

Have you tried constructing your URL using one of the examples in https://github.com/Yelp/yelp-api/tree/master/v2 and comparing the result to your string?

**Comment by clizarralde** [comment]
I am having the same issue.

**Comment by dan98765** [comment]
We are in the process of archiving this API v2 github repository, and as part of that are closing out all issues. 

---
Announcement:
As of June 30, 2018, the API v2 has been discontinued and v2 endpoints no longer work. It has been replaced by [Yelp's Fusion API](https://www.yelp.com/fusion). This github repository is archived. There is a new Yelp Fusion-specific github repository at https://github.com/Yelp/yelp-fusion.
