### ISSUE TITLE
Full Neighborhood listing?

### ISSUE THREAD

**Issue by vkman** [Yelp/yelp-api#147]
Hello, 
I'm working on an app that makes use of the Yelp API, and would like to present the user with an autofill of Yelp-supported regions.  I've imported the hierarchical [neighborhood list here](https://www.yelp.com/developers/documentation/v2/neighborhood_list), but searching the Yelp site shows this is just a fraction of regions supported.  Are there any APIs for accessing a more full listing, or is there a chance the neighborhood page will get updated?

Thanks for any info.

**Comment by mittonk** [comment]
@vkman : What's an example neighborhood?

**Comment by vkman** [comment]
Do you mean an example of a neighborhood not listed on the page but still has Yelp results?
There are many --  Jersey City, NJ;  Ft. Lauderdale, FL;  Anchorage, AK;  all of Puerto Rico.  Even whole countries like The Philippines are missing from the list.  
That is, if I'm understanding your question correctly.

**Comment by mittonk** [comment]
OK, that helps.

Yelp supports lots (millions? billions?) of search locations, including specific lat-long points; only a few of these are "Neighborhood" entities, which have some extra manually-curated metadata.  The page you're looking at only lists "Neighborhood" entities.

"Jersey City, NJ" is a search location, but it is not a "Neighborhood".

"107 Main St, Cambridge, MA" is also a valid search location which isn't a Neighborhood entity.

You're not limited to these locations when searching.

**Comment by vkman** [comment]
I understand and I'm definitely not looking for a list addresses or lat/long points, but just a more complete listing of supported cities & neighborhoods.  If this is not available/too exhaustive, is there perhaps just a listing of cities in the Yelp realm?  Once again, thank you for responding promptly.

**Comment by watterso** [comment]
@vkman unfortunately going into detail on how we do [geocoding](https://en.wikipedia.org/wiki/Geocoding) is outside the scope of our api support and generally not public knowledge. However you can expect that we do are best to support all locations in the countries for which we are launched, so have a look at the bottom of our [factsheet](https://www.yelp.com/factsheet) to see which markets Yelp has entered.

**Comment by vkman** [comment]
Ok, thank you.
