### ISSUE TITLE
re: Posting a response to comment using yelp api

### ISSUE THREAD

**Issue by minhDtran** [Yelp/yelp-api#148]
Hello,
  I am new on yelp , and I would like to learn if I can post a response to a comment using yelp api.
If you happen to know how , please share it with me. Thank you and I am using python for yelp api.

Tom

**Comment by butterfield** [comment]
Hey Tom!

This API is currently read-only, so unfortunately that functionality isn't supported.

**Comment by minhDtran** [comment]
Thank you for the reply. If you would not mind, may I ask you one more
question , please ?
Is there any other way if I would like to posy a response to yelp comment
using other mean than the yelp api?

Many thanks for all of the helps,
Tom

**Comment by mittonk** [comment]
@minhDtran : If you're the business owner, you can claim the business on biz.yelp.com and respond to reviews there.
