### ISSUE TITLE
Recent Reviews By Area

### ISSUE THREAD

**Issue by bretwalker** [Yelp/yelp-api#150]
I'm trying to find recent reviews for Louisville, Ky.
According to the [documentation](https://www.yelp.com/developers/documentation/v2/additional_resources), an RSS feed should be available on the city's page:

| Feed Name | Feed Description  | How To Obtain  |
|---|---|---|
| Recent Reviews By Area  | Provides access to recent reviews for a particular area  | The landing page for a particular city  |

I've looked on [Louisville's landing page](https://www.yelp.com/louisville), but I don't see any RSS links (I've also checked the source).

Where can I find the recent reviews RSS feed?

**Comment by tomelm** [comment]
Hey @bretwalker, we've removed this feature. We'll update the documentation page to reflect that, sorry about the confusion

**Comment by bretwalker** [comment]
@tomelm, that's very disappointing. That feed was very useful. I hope Yelp will reconsider.
