### ISSUE TITLE
Need to get More than 1000 records

### ISSUE THREAD

**Issue by krishnarajtech** [Yelp/yelp-api#153]
Hello team,
I cant able to access more than 1000 records from search api request.

****Sample API URL::https://api.yelp.com/v2/search?term=cream+puffs&location=San+Francisco****

I have get the following error when I try to access more than 1000 records.

Fatal error: Curl failed with error #400: {"error": {"field": "offset", "description": "The maximum number of accessible results is 1000", "id": "INVALID_PARAMETER", "text": "One or more parameters are invalid in request"}} 

Thanks in Advance

**Comment by mittonk** [comment]
@krishnarajtech : Hm, 1000 is indeed the limit.  What's your use case for wanting more than that?

**Comment by mittonk** [comment]
Working as expected, closing.

**Comment by gurkpet** [comment]
I'm also hoping for more than 1000 results.  I'm a data science student and I am trying to set up analysis that would allow me to locate places in x state that have a lower concentration of x type of restaurants per population.  The limit on 4000 meters is also proving to be problematic.  Is there a way to work around this or am I out of luck?

**Comment by BhanushankarJoshi** [comment]
am i able to fetch next 1000 record (*next day) then how will i keep track ?
