### ISSUE TITLE
Error: The OAuth credentials are invalid

### ISSUE THREAD

**Issue by thatryan** [Yelp/yelp-api#156]
Hi there, two issues. 

Using PHP version of sample code, I could not get anything to work using the `$GLOBALS` however when I changed functions from `$GLOBALS['BUSINESS_PATH'] . urlencode($business_id);` to `BUSINESS_PATH . urlencode($business_id)` etc that issue cleared up.

Secondly I continuously get the OAuth error invalid credentials. It appears maybe the signature is not being built correctly for me?

`https://api.yelp.com/v2/business/BIZ-ID?oauth_consumer_key=&oauth_nonce=NONCE&oauth_signature=SIG%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1469204949&oauth_token=&oauth_version=1.0`

The `consumer_key` and `oauth_token` appear to be empty...

Any thoughts? Thanks!

**Comment by mittonk** [comment]
@thatryan : Did you remember to fill your own OAuth credentials in here?
* https://github.com/Yelp/yelp-api/blob/master/v2/php/sample.php#L25

**Comment by thatryan** [comment]
Yes, I create a `yelp.php` file that I include in my main PHP file.
Looks like this,
https://gist.github.com/4b14d22ca97b4a1aaf85c5afa1fd7ab8

Inside my main PHP file, I call it like this,

https://gist.github.com/a92005f4d20e22e8a44de55b3c177b2e

**Comment by thatryan** [comment]
I am trying to follow the code in `OAuth.php` is it expecting the parameters to be in `$_POST` somewhere?

**Comment by mittonk** [comment]
Hm, I suspect something's going wrong on this line in your code:
` $consumer = new OAuthConsumer($CONSUMER_KEY, $CONSUMER_SECRET);`

I'd suggest using a debugger or print statements to see the values of `$CONSUMER_KEY` and `$consumer`, and compare them against the similar line in the Yelp sample code.
