### ISSUE TITLE
Error Code 400

### ISSUE THREAD

**Issue by ilikepotatoes1** [Yelp/yelp-api#158]
Using the yelp-android api, i get

```
code = 400
errorID = "INVALID_SIGNATURE"
message = "Bad Request"
text = "Signature was invalid"
```

This error starting popping up randomly and i've generated new token and secret codes but the error still persists. Lots of suggestions but nothing helped

Thanks in advance

**Comment by mittonk** [comment]
1. What's an example signed URL?  Replace the private values with "XXX" or "REDACTED" or similar before posting.

2. Does this only hit certain searches --- those with accents, or spaces, or other tricky characters?
