### ISSUE TITLE
API search not returning accurate results

### ISSUE THREAD

**Issue by MarkXMx** [Yelp/yelp-api#159]
For instance, form the YELP API Console run a search:
https://api.yelp.com/v2/search/?term=3 FORTY GRILL&location=340 SINATRA DRIVE, HOBOKEN, NJ
you get 30 business, no one is even close to the one provided in the search. 
Whereas, this is the business: https://www.yelp.com/biz/3-forty-grill-hoboken
Is not returned in the 30 results.
This happens with many other cases.

**Comment by mittonk** [comment]
@MarkXMx : 

https://www.yelp.com/biz/3-forty-grill-hoboken is marked "Closed".  The web page has the banner "Yelpers report this location has closed." and it's been closed long enough (looks like ~1.5 years) that it doesn't appear in www.yelp.com searches either.
