### ISSUE TITLE
API V3 results are not sorted by distance

### ISSUE THREAD

**Issue by galskari** [Yelp/yelp-api#160]
Hi Community,
I am sending the following request:

https://api.yelp.com/v3/businesses/search?sort_by=distance&term=coffee+place&location=1090+folsom+St+San+Francisco

I get blue-bottle-coffee-co-san-francisco-7 as the first result. However, sightglass-coffee-san-francisco is closer to this location. It seems that no matter what address I send around this area I get the same sort. Even when I am requesting one block form sightglass-coffee-san-francisco.

This is the response I get:

{
  "total": 4366,
  "businesses": [
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94103",
        "address1": "66 Mint St",
        "address2": ""
      },
      "price": "$$",
      "image_url": "http://s3-media2.fl.yelpcdn.com/bphoto/YKoMObZPbtVi1l7f3g4xwg/o.jpg",
      "url": "https://www.yelp.com/biz/blue-bottle-coffee-co-san-francisco-7",
      "review_count": 1849,
      "rating": 4,
      "id": "blue-bottle-coffee-co-san-francisco-7",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "phone": "+15106533394",
      "name": "Blue Bottle Coffee Co",
      "coordinates": {
        "latitude": 37.782352,
        "longitude": -122.407697
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94102",
        "address1": "315 Linden St",
        "address2": ""
      },
      "price": "$$",
      "image_url": "http://s3-media2.fl.yelpcdn.com/bphoto/0quAAk1_A42TYCNen-t7Tw/o.jpg",
      "url": "https://www.yelp.com/biz/blue-bottle-coffee-san-francisco-8",
      "review_count": 1673,
      "rating": 4.5,
      "id": "blue-bottle-coffee-san-francisco-8",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "phone": "+15106533394",
      "name": "Blue Bottle Coffee",
      "coordinates": {
        "latitude": 37.77638,
        "longitude": -122.423211
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94102",
        "address1": "748 Van Ness Ave",
        "address2": ""
      },
      "price": "$",
      "image_url": "http://s3-media1.fl.yelpcdn.com/bphoto/5FNv-ZL4UayQsk2CyWxpoA/o.jpg",
      "url": "https://www.yelp.com/biz/philz-coffee-san-francisco-4",
      "review_count": 1436,
      "rating": 4.5,
      "id": "philz-coffee-san-francisco-4",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "phone": "+14152927660",
      "name": "Philz Coffee",
      "coordinates": {
        "latitude": 37.782383,
        "longitude": -122.420526
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94108",
        "address1": "90 Grant Ave",
        "address2": null
      },
      "price": "$$",
      "image_url": "http://s3-media2.fl.yelpcdn.com/bphoto/VWFULcZ8UAqu7wfts7m-8A/o.jpg",
      "url": "https://www.yelp.com/biz/nespresso-boutique-bar-san-francisco-2",
      "review_count": 300,
      "rating": 4,
      "id": "nespresso-boutique-bar-san-francisco-2",
      "categories": [
        {
          "alias": "cafes",
          "title": "Cafes"
        },
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "phone": "+18005621465",
      "name": "Nespresso Boutique Bar",
      "coordinates": {
        "latitude": 37.7875580638647,
        "longitude": -122.404947951436
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94103",
        "address1": "375 Valencia St",
        "address2": ""
      },
      "price": "$",
      "image_url": "http://s3-media2.fl.yelpcdn.com/bphoto/xs4GEA2BOpPYG7bh7o6GrA/o.jpg",
      "url": "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      "review_count": 1758,
      "rating": 4,
      "id": "four-barrel-coffee-san-francisco",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "phone": "+14152520800",
      "name": "Four Barrel Coffee",
      "coordinates": {
        "latitude": 37.7670169511878,
        "longitude": -122.42184275
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94158",
        "address1": "201 Berry St",
        "address2": ""
      },
      "price": "$",
      "image_url": "http://s3-media3.fl.yelpcdn.com/bphoto/hG9NWfPbnnY-yrsX0FcqOA/o.jpg",
      "url": "https://www.yelp.com/biz/philz-coffee-san-francisco-3",
      "review_count": 1318,
      "rating": 4.5,
      "id": "philz-coffee-san-francisco-3",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        },
        {
          "alias": "sandwiches",
          "title": "Sandwiches"
        }
      ],
      "phone": "+14158759943",
      "name": "Philz Coffee",
      "coordinates": {
        "latitude": 37.775558280936,
        "longitude": -122.39338696954
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94103",
        "address1": "270 7th St",
        "address2": ""
      },
      "price": "$$",
      "image_url": "http://s3-media4.fl.yelpcdn.com/bphoto/b59PUT6mZNZEXraIUNGagw/o.jpg",
      "url": "https://www.yelp.com/biz/sightglass-coffee-san-francisco",
      "review_count": 1347,
      "rating": 4,
      "id": "sightglass-coffee-san-francisco",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "phone": "+14158611313",
      "name": "Sightglass Coffee",
      "coordinates": {
        "latitude": 37.77696,
        "longitude": -122.40851
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94110",
        "address1": "1890 Bryant St",
        "address2": ""
      },
      "price": "$",
      "image_url": "http://s3-media1.fl.yelpcdn.com/bphoto/qCMuF6XZpzYm5NYuo3TgzQ/o.jpg",
      "url": "https://www.yelp.com/biz/coffee-bar-san-francisco",
      "review_count": 918,
      "rating": 4,
      "id": "coffee-bar-san-francisco",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        },
        {
          "alias": "sandwiches",
          "title": "Sandwiches"
        }
      ],
      "phone": "+14155518100",
      "name": "Coffee Bar",
      "coordinates": {
        "latitude": 37.7631622208,
        "longitude": -122.411044473128
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94103",
        "address1": "1246 Folsom St",
        "address2": ""
      },
      "price": "$",
      "image_url": "http://s3-media3.fl.yelpcdn.com/bphoto/yTY5NYpZ0vLIO6t4OZHNug/o.jpg",
      "url": "https://www.yelp.com/biz/vega-cafe-san-francisco",
      "review_count": 116,
      "rating": 4.5,
      "id": "vega-cafe-san-francisco",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "phone": "+14152601262",
      "name": "Vega Cafe",
      "coordinates": {
        "latitude": 37.7745635,
        "longitude": -122.410969
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94107",
        "address1": "893A Folsom St",
        "address2": ""
      },
      "price": "$$",
      "image_url": "http://s3-media1.fl.yelpcdn.com/bphoto/nyU0_VLKzCxfDBbiywKBIw/o.jpg",
      "url": "https://www.yelp.com/biz/elite-audio-coffee-bar-san-francisco",
      "review_count": 157,
      "rating": 4.5,
      "id": "elite-audio-coffee-bar-san-francisco",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "phone": "+14157951149",
      "name": "Elite Audio Coffee Bar",
      "coordinates": {
        "latitude": 37.7802696228027,
        "longitude": -122.402862548828
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94103",
        "address1": "15th & Kansas SE Corner",
        "address2": ""
      },
      "price": "$",
      "image_url": "http://s3-media1.fl.yelpcdn.com/bphoto/W_xxOnU2PMDhZHk3CdMkjQ/o.jpg",
      "url": "https://www.yelp.com/biz/papa-november-san-francisco",
      "review_count": 78,
      "rating": 4.5,
      "id": "papa-november-san-francisco",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "name": "Papa November",
      "coordinates": {
        "latitude": 37.7672036024795,
        "longitude": -122.403616905212
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94102",
        "address1": "399 Golden Gate Ave",
        "address2": ""
      },
      "price": "$",
      "image_url": "http://s3-media1.fl.yelpcdn.com/bphoto/pSZ9UoxzkxF3vaHK4eWfZw/o.jpg",
      "url": "https://www.yelp.com/biz/philz-coffee-san-francisco-8",
      "review_count": 339,
      "rating": 4.5,
      "id": "philz-coffee-san-francisco-8",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "phone": "+14156217000",
      "name": "Philz Coffee",
      "coordinates": {
        "latitude": 37.7813806997337,
        "longitude": -122.417041361332
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94104",
        "address1": "101 Montgomery St",
        "address2": ""
      },
      "price": "$$",
      "image_url": "http://s3-media2.fl.yelpcdn.com/bphoto/aaeTwPiMFuzevIgVWnGjmQ/o.jpg",
      "url": "https://www.yelp.com/biz/coffee-bar-san-francisco-2",
      "review_count": 261,
      "rating": 4,
      "id": "coffee-bar-san-francisco-2",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "phone": "+14153972233",
      "name": "Coffee Bar",
      "coordinates": {
        "latitude": 37.7903925,
        "longitude": -122.4021594
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94102",
        "address1": "986 Market St",
        "address2": ""
      },
      "price": "$$",
      "image_url": "http://s3-media1.fl.yelpcdn.com/bphoto/KSRp4RauP-QgtaiIBNu_pQ/o.jpg",
      "url": "https://www.yelp.com/biz/equator-coffees-and-teas-san-francisco",
      "review_count": 79,
      "rating": 4,
      "id": "equator-coffees-and-teas-san-francisco",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "phone": "+14156149129",
      "name": "Equator Coffees & Teas",
      "coordinates": {
        "latitude": 37.7826422914878,
        "longitude": -122.409869469702
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94103",
        "address1": "353 10th St",
        "address2": ""
      },
      "price": "$",
      "image_url": "http://s3-media2.fl.yelpcdn.com/bphoto/HtKc3ZLX5vLSG9Oo2ra0EQ/o.jpg",
      "url": "https://www.yelp.com/biz/capricorn-coffees-and-teas-san-francisco",
      "review_count": 70,
      "rating": 4.5,
      "id": "capricorn-coffees-and-teas-san-francisco",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "phone": "+14156218500",
      "name": "Capricorn Coffees & Teas",
      "coordinates": {
        "latitude": 37.772308,
        "longitude": -122.411804
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94102",
        "address1": "142 McAllister St",
        "address2": ""
      },
      "price": "$",
      "image_url": "http://s3-media2.fl.yelpcdn.com/bphoto/buZRfFLJSi9WZiNdTC7UJg/o.jpg",
      "url": "https://www.yelp.com/biz/celtic-coffee-company-san-francisco",
      "review_count": 185,
      "rating": 4,
      "id": "celtic-coffee-company-san-francisco",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        },
        {
          "alias": "sandwiches",
          "title": "Sandwiches"
        },
        {
          "alias": "bagels",
          "title": "Bagels"
        }
      ],
      "phone": "+14152550208",
      "name": "Celtic Coffee Company",
      "coordinates": {
        "latitude": 37.7809433,
        "longitude": -122.4144406
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94108",
        "address1": "25 Maiden Ln",
        "address2": null
      },
      "price": "$",
      "image_url": "http://s3-media1.fl.yelpcdn.com/bphoto/_eMt3Li_B5DdeAkHFsxIJA/o.jpg",
      "url": "https://www.yelp.com/biz/iron-horse-coffee-bar-san-francisco",
      "review_count": 59,
      "rating": 4.5,
      "id": "iron-horse-coffee-bar-san-francisco",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "name": "Iron Horse Coffee Bar",
      "coordinates": {
        "latitude": 37.7882923185825,
        "longitude": -122.404029965401
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94107",
        "address1": "372 Ritch St",
        "address2": ""
      },
      "price": "$",
      "image_url": "http://s3-media4.fl.yelpcdn.com/bphoto/5mOWorADV__loMOFwolkug/o.jpg",
      "url": "https://www.yelp.com/biz/cento-san-francisco",
      "review_count": 201,
      "rating": 4.5,
      "id": "cento-san-francisco",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "phone": "",
      "name": "Cento",
      "coordinates": {
        "latitude": 37.778745250608,
        "longitude": -122.39396334359
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94103",
        "address1": "1415 Folsom St",
        "address2": ""
      },
      "price": "$",
      "image_url": "http://s3-media3.fl.yelpcdn.com/bphoto/oczmxdUew6mn4nkuhI2woQ/o.jpg",
      "url": "https://www.yelp.com/biz/sextant-coffee-roasters-san-francisco",
      "review_count": 104,
      "rating": 4,
      "id": "sextant-coffee-roasters-san-francisco",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "phone": "+14153551415",
      "name": "Sextant Coffee Roasters",
      "coordinates": {
        "latitude": 37.7726446261622,
        "longitude": -122.412992231548
      }
    },
    {
      "location": {
        "address3": "",
        "state": "CA",
        "city": "San Francisco",
        "country": "US",
        "zip_code": "94109",
        "address1": "1415 Larkin St",
        "address2": ""
      },
      "price": "$$",
      "image_url": "http://s3-media4.fl.yelpcdn.com/bphoto/42V-yDiNZcfLFT743jxmPA/o.jpg",
      "url": "https://www.yelp.com/biz/contraband-coffee-bar-san-francisco",
      "review_count": 592,
      "rating": 4,
      "id": "contraband-coffee-bar-san-francisco",
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "phone": "+14158397388",
      "name": "Contraband Coffee Bar",
      "coordinates": {
        "latitude": 37.791405,
        "longitude": -122.419327
      }
    }
  ]
}

**Comment by tomelm** [comment]
Hey @galskari, I'm going to close this ticket so we can discuss it in the v3 docs repo (https://github.com/Yelp/yelp-api-v3/issues/29)
