### ISSUE TITLE
Yelp API not returning data for one of my clients

### ISSUE THREAD

**Issue by btaitano** [Yelp/yelp-api#163]
I have been debugging the issue but it all points to Yelp API not returning data based on the client's phone number: 7137776453
http://www.1800dentist.com/dentists/dr-ronald-moon/web-ugc/

I have checked other client profiles and there are no issues, for example:
http://www.1800dentist.com/dentists/bijan-family-dental-practice/web-ugc/
http://www.1800dentist.com/dentists/dr-bhairavi-sheth/web-ugc/

Please help me find out why this certain client has the issue. It only appears to be happening to this client.

**Comment by FYJen** [comment]
Hi @btaitano :

Could you post the phone search queries here for all three businesses?
That would help us identify the issue.

**Comment by mittonk** [comment]
@btaitano : What Yelp listing do you expect to find?

https://www.yelp.com/biz/ronald-j-moon-dds-the-dental-cosmetic-center-of-houston-houston-5 has a different phone number (and is marked closed).

**Comment by mittonk** [comment]
That phone number matches:
* https://www.yelp.com/biz/moon-cosmetic-dentistry-houston-3

which had no businesses in Aug 2016, when this issue was filed.

It does now, and seems to be working as expected.

The Yelp API does not provide information on businesses without reviews.
