### ISSUE TITLE
Update to the Windows Phone Yelp! App?

### ISSUE THREAD

**Issue by josetheveg** [Yelp/yelp-api#166]
Are we going to see an update any time soon to the Windows Phone Yelp! app? It's seems overdue. Lacking many options and it seems so far behind the app on other OSes. Thank you!

**Comment by mittonk** [comment]
@josetheveg : That sounds like good input for the Microsoft Store page:
* https://www.microsoft.com/en-us/store/p/yelp/9wzdncrfj2jn

(Not directly part of the Yelp API, not much more to say in this Github project.)

**Comment by mittonk** [comment]
(Ah, I see you've already found that.)
