### ISSUE TITLE
Yelp not returning display_phone

### ISSUE THREAD

**Issue by SuzHarrison** [Yelp/yelp-api#167]
my app has broken today due to the following error - has there been a change to the API?

undefined method `[]' for nil:NilClass display_phone

Thanks in advance!

**Comment by mittonk** [comment]
@SuzHarrison : 
1. Are you using /v2 or /v3 endpoints?  Which specific endpoint?

2. Are you using a library like https://github.com/Yelp/yelp-ios ?  If so, which one in particular?

**Comment by SuzHarrison** [comment]
Problem in my code! So sorry!
