### ISSUE TITLE
PokeStop filter is gone

### ISSUE THREAD

**Issue by jlevente** [Yelp/yelp-api#169]
Hi,

I'm a PhD candidate at University of Florida and I'm conducting an academic research about the "Geography of Pokemons". One of my research questions aimed to deal with the aspects of how the public interact with this new trend (i.e. people are crazy about it and go catch Pokemons everywhere). Your example of using PokeStops nearby property on businesses was a nice example of it and it would've been a great addition to my research by being able to analyze how Yelp users added this tag to a business. The offset between these business and the real locations of PokeStops would have revealed interesting patterns about the spatial distribution of Yelp businesses and real PokeStop locations, like how close they are to each other or if there's a higher probability of tagging a business with this tag if there are more Pokemons locations nearby, etc.

However, as I noticed now, PokeStop filter is gone. I was using API v2 to grab a dataset to work with including business tagged as PokeStop nearby but now I'm unable to do so. As I recall, last week it worked as expected. Also noticed that "PokeStop nearby" is not included in the "More business info" of the website. I did not store any data from my previous experiments so as it seems I'd need to drop using Yelp from my research.

I understand that it's not the intended use of Yelp API but I was wondering if there still was a way to access this information - solely for academic purposes (it's not included in the Yelp data challenge dataset and my study areas don't intersect with those unfortunately).

Thanks for any info you can give me on this topic. Also, as my questions is not technical and not closely related to any of the API issues, feel free to point me to the right direction where I could get in contact with the right branch of the company.

Best,
Levente

**Comment by mittonk** [comment]
@jlevente : Hm, let me look into this.

**Comment by tomelm** [comment]
@jlevente could you clarify how you were using the PokeStop filter through the API?

**Comment by jlevente** [comment]
@mittonk @tomelm thanks guys for looking into this.

I was using the search API with `term` and `bounds` filters. `term` was set to `PokeStop` or `PokeStop nearby` ( I can't recall exactly what I used last week) but now it's the same. sample code with the Python yelp-python:

```python
params = {
    "term": "PokeStop",
    "limit": 20
}
res = client.search_by_bounding_box(26.064956,-80.241394,26.096101,-80.210495, **params)```

gives no result, however I know for sure that this venue (https://www.yelp.com/biz/steves-espresso-davie-3) should have been returned (as I was the one who added `PokeStop nearby` a while back).

**Comment by jlevente** [comment]
and actually, businesses with `PokeStop` mentions in reviews are still being returned by `term=PokeStop` though.

**Comment by mittonk** [comment]
OK, looks like this is part of a tradeoff we're making in the search backend; we're still getting terms-in-reviews matches, but no longer matching the attribute value.

Need to discuss the tradeoffs internally for a while, but this isn't just a simple bug fix.

**Comment by jlevente** [comment]
Thanks for the update. Ping me when you decide and there's a way to match attributes again? @mittonk

**Comment by tomelm** [comment]
Pokestop is not around anymore so there's no way to filter this data, closing.
