### ISSUE TITLE
Getting full reviews

### ISSUE THREAD

**Issue by alexwhin** [Yelp/yelp-api#170]
Hi,

After working with 3.0 I can't seem to find any way of pulling out full review listing, is this possible?
Any help would be very much appreciated.

Best regards,
Alex

**Comment by d9chen** [comment]
Hi @Alexwhin, by 'full review listing' do you mean all reviews for a given business? If so 2.0 does not offer that capability. The [business API documentation page]( https://www.yelp.com/developers/documentation/v2/business) offers a good example on what you can  expect from responses containing review information.
