### ISSUE TITLE
No results for category_filter with fishing

### ISSUE THREAD

**Issue by SchlegelThomas** [Yelp/yelp-api#171]
Hi, 
I've been using the yelp search api v2.0 for a while now.  We recently expanded our category selection on our site and have included 'fishing'.  However, when testing I'm not getting expected data from the api. 

Here is a link to some results I can achieve just through your site: https://www.yelp.com/search?find_desc=fishing&find_loc=Guntersville,+AL&start=0&cflt=fishing&l=g:-86.18007116546937,34.44428043912148,-86.38606481781312,34.27422969834631

I'm attempting to make the request with these params: 

term=fishing
ll=34.44428043912148,-86.18007116546937
radius_filter=40000
category_filter=fishing

+ all of the required oauth secrets and tokens.

When I include category_filter=fishing  I get 0 results, when I remove the category_filter I get results but none of them seem to be related to fishing, but instead grouped under ActiveLife or restaurants.
I've tried changing the terms and category_filter in all combinations of categories and subcategories but nothing seems to come back for fishing.  I've also tried adjusting my radius and coords, but no luck.
Any direction would be appreciated!

Thanks,

Thomas.

**Comment by mittonk** [comment]
@SchlegelThomas : The five examples I see on your www.yelp.com search all have 0 reviews, which means they're not accessible through the Yelp API.  Sorry!

When you remove the category filter, you're indeed getting restaurants where people's reviews talk about "came here after fishing" or similar.
