### ISSUE TITLE
monetizing

### ISSUE THREAD

**Issue by daniellabirch** [Yelp/yelp-api#172]
The Yelp [display requirements](https://www.yelp.com/developers/display_requirements) state:
"You can monetize your apps and sites to your heart’s content -- we don’t require any sort of revenue share - but don’t create tools for sale that extend Yelp functionality (such as Facebook integration)."

I'm making an app that incorporates bike share locations with local business and I'm using Yelp to provide local biz info. Does that count as "extending Yelp functionality"?

Also, speaking of monetizing my app. I've never done that before. Do you have any advice on how I could go about doing that?

**Comment by mittonk** [comment]
On the monetizing front: There are a bunch of approaches; the most common are including ads in your app, or charging for your app in the Android / Apple / whatever store.

(I'm not qualified to interpret the legalese in the display requirements.)
