### ISSUE TITLE
Unable to get a full review for myself

### ISSUE THREAD

**Issue by bradcypert** [Yelp/yelp-api#173]
Is it possible to get a full, non-truncated review for a given user? The closest thing I could find was my RSS feed, but it truncates the review part of the way through.

I really think this should be exposed, as it's what helps make Yelp unique and is a primary reason to even want to use your API.

**Comment by mittonk** [comment]
@bradcypert : Full review text isn't available.  What's your use case?

**Comment by bradcypert** [comment]
@mittonk: I'm playing with Rust and decided to create a pet project to learn the language. I thought it'd be a fun idea to be able to pull a specific users reviews and allow them to generate a static website from it with their reviews, acting as basically a food critic blog.

**Comment by rob-derosa** [comment]
I would also like to have the option of returning the full review. Use case is to run sentiment analysis on the review to see if it matches the rating given.

**Comment by tomelm** [comment]
@bradcypert @rob-derosa I would recommend you checkout the dataset we have available from the dataset challenge: yelp.com/dataset_challenge

It'll give you a couple of million reviews to try this out with :). The caveats here are that the dataset is for purely educational purposes and is not "fresh".
