### ISSUE TITLE
access token for api v3 doesn't work

### ISSUE THREAD

**Issue by compworkmail** [Yelp/yelp-api#174]
I have created new API v3 app, received client id and secret, received access token and try to sign my request to retrieve reviews, but I have an error:
request:

curl --header "access_token: my_token_here" https://api.yelp.com/v3/businesses/sugarfoot-san-francisco/reviews

error:
{"error": {"code": "TOKEN_MISSING", "description": "An access token must be supplied in order to use this endpoint."}}

**Comment by mittonk** [comment]
@compworkmail : In CURL syntax, aim for:
```
curl \
  -X GET \
  --header "Authorization: Bearer TokenYouGotFromOauth2TokenEndpoint" \
  "https://api.yelp.com/v3/businesses/search?term=food&location=boston"
```
Note that the header is "Authorization" (not "access_token") and the value includes "Bearer " before your actual token.

**Comment by compworkmail** [comment]
thanks. It would be great if you will add this example to your API v3 documentation to avoid new misunderstandings.
