### ISSUE TITLE
official API v3 php library

### ISSUE THREAD

**Issue by compworkmail** [Yelp/yelp-api#175]
Hello developers team. As I see v3 API is now main on developers site of yelp, but why there is now official or even unofficial php v3 library yet created? Are you planing to create v3 php library or this new API for now only in testing mode and you don't plan to create any libraries for it at all? If you will create it, when it will be approximately? Thanks.

**Comment by mittonk** [comment]
We haven't figured out the timing yet --- we'll share more details as we work them out.
