### ISSUE TITLE
Business Reviews API always returns 1 review

### ISSUE THREAD

**Issue by chribsen** [Yelp/yelp-api#177]
I am currently using the `/v3/businesses/{id}/reviews` to retrieve the most recent reviews for a company. However after doing some unit testing on your endpoints it seems like the endpoint is always returning max. 1 review without pagination possibility when `total` > 1:

```
{
    "reviews": [
        {
            "rating": 4,
            "text": "Very delicious and well done food!! Gourmet to\nThe core!! I recommend this place 100%, if you are looking for a good beer don't look any further, the beer...",
            "time_created": "2015-05-01 12:48:59",
            "url": "https://www.yelp.com/biz/davids-stege-2?hrid=ShBLcOoJh7Ry3XYcM-mskg&adjust_creative=jlFOclSGS5AQzZGXSMWVbg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=jlFOclSGS5AQzZGXSMWVbg",
            "user": {
                "image_url": null,
                "name": "Flemming J."
            }
        }
    ],
    "total": 3
}
```
Is this the intended behaviour? The following documentation seems to suggest otherwise (e.g. the  `response body` used as an example has `total=3` and returns an array with 3 reviews): https://www.yelp.com/developers/documentation/v3/business_reviews

Thanks!

**Comment by mittonk** [comment]
@chribsen : Your example business only has 1 review in English; see https://www.yelp.com/biz/davids-stege-2 .

There's also a Danish review, which you can get by adding `locale=da_DK` to your request from https://www.yelp.com/developers/documentation/v3/supported_locales .

Yelp Fusion supports returning a maximum of three reviews in a language --- see a business like `next-door-cafe-københavn-3` with more than three reviews.

Does that give you enough to run with?

**Comment by chribsen** [comment]
Thanks! Adding url argument `?locale=dk_DK` solved the problem. Maybe this parameter (along with any other optional parameters) can be added to the _Parameter_ section under the endpoint? https://www.yelp.com/developers/documentation/v3/business_reviews

**Comment by mittonk** [comment]
Definitely, doing that as part of
* https://github.com/Yelp/yelp-fusion/issues/3

(Forgot to leave a note over here, whoops.)

**Comment by mittonk** [comment]
`locale` is now listed on 
* https://www.yelp.com/developers/documentation/v3/business_reviews
