### ISSUE TITLE
I am getting only 14 businesses at a time instead of 20 in  business api

### ISSUE THREAD

**Issue by NikitaTurakhia** [Yelp/yelp-api#178]
hello @tomelm  and @mittonk ,

I am using api v3.
When I run business api for restaurants, I am getting only 14 businesses instead of 20 and while I enter pizza as a term in business  api, I am getting only 3 searches.

Thanks.

**Comment by mittonk** [comment]
@NikitaTurakhia : Sounds like this was the same thing you reported in
* https://github.com/Yelp/yelp-fusion/issues/87

Let's keep discussing in 
* https://github.com/Yelp/yelp-fusion/issues/92

Closing this one.
