### ISSUE TITLE
Ajax request error - React App

### ISSUE THREAD

**Issue by matiasironyard** [Yelp/yelp-api#179]
Hi,

I'm in the process of creating a client where the user inputs their business phone number and the app creates their profile using the phone number search results . I'm currently trying to do a get request as follows, but I get this error:

XMLHttpRequest cannot load https://api.yelp.com/v3/businesses/search/phone?phone=%2018645955240. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access. The response had HTTP status code 500.

here is the code:

var settings = {
  "async": true,
  "crossDomain": true,
  "url": "https://api.yelp.com/v3/businesses/search/phone?phone=%2018645955240",
  "method": "GET",
  "headers": {
    "authorization": "Bearer mytoken",
  }
}

$.ajax(settings).done(function (response) {
  console.log(response);
});

I am working locally from my machine. What am I missing?

Thank you for your help!

**Comment by mittonk** [comment]
@matiasironyard : Sounds like you're trying to do cross-origin resource sharing (CORS); we don't support that flow.

See https://github.com/Yelp/yelp-fusion/issues/44 for details and alternatives.

**Comment by faresallolo** [comment]
Hi, 
may you clarify a few things for me please. I am building an app and need to get Hours of operation. I noticed only yelp v3 has it. So, I tried it using angularjs and I got into this same issue with jsonp. 

I have tried $httpProvider.interceptors , $sceDelegateProvider.resourceUrlWhitelist, and $http.dafults.headers.common but I had no luck.

Even though, this works perfectly : 
curl   -X GET   -H "Authorization: Bearer "access_token"    "https://api.yelp.com/v3/businesses/
in terminal why is it not allowed in a web app or hybrid mobile app. Last thing is,  I haven't tried that yet but on corss-platform like ionic will it work ? or it will be the same issue.?

I would like to point that the v2 with Ouath works with no problem on ionic; however, is it troubling or risky to provide Hours of operation on v2 ?

Thanks in advance.
