### ISSUE TITLE
Invalid Parameters

### ISSUE THREAD

**Issue by xal629** [Yelp/yelp-api#181]
![screen shot 2017-01-02 at 9 26 51 am](https://cloud.githubusercontent.com/assets/24877869/21592473/4fea33e2-d0d3-11e6-9519-2803d6beafab.png)
![screen shot 2017-01-02 at 9 27 15 am](https://cloud.githubusercontent.com/assets/24877869/21592470/4fe88bd2-d0d3-11e6-86a2-bf77af42b39e.png)
![screen shot 2017-01-02 at 9 27 27 am](https://cloud.githubusercontent.com/assets/24877869/21592472/4fe94d38-d0d3-11e6-8d75-7c97fd341a69.png)
![screen shot 2017-01-02 at 9 27 48 am](https://cloud.githubusercontent.com/assets/24877869/21592471/4fe8cafc-d0d3-11e6-9592-f0eab2554550.png)

Need help getting Yelp to load on my site... yelp tech support pointed me here instead of helping... super frustrated. Please advise if you can... thanks.

**Comment by mittonk** [comment]
@xal629 : Looks like you're using the non-Yelp "Yelp Widget Pro":
* https://wordpress.org/plugins/yelp-widget-pro/

We can't provide support for that 3rd party product --- please check out their FAQ, I suspect they want less data in the "Business ID" box:
* https://wordpress.org/plugins/yelp-widget-pro/faq/

**Comment by xal629** [comment]
What is the correct app/widget? This is what pulls up for wordpress.


Sent via the Samsung Galaxy S7 active, an AT&T 4G LTE smartphone
-------- Original message --------From: Ken Mitton <notifications@github.com> Date: 1/2/17  3:57 PM  (GMT-06:00) To: Yelp/yelp-api <yelp-api@noreply.github.com> Cc: xal629 <krishersh@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [Yelp/yelp-api] Invalid Parameters (#181) 
@xal629 : Looks like you're using the non-Yelp "Yelp Widget Pro":

https://wordpress.org/plugins/yelp-widget-pro/

We can't provide support for that 3rd party product --- please check out their FAQ, I suspect they want less data in the "Business ID" box:

https://wordpress.org/plugins/yelp-widget-pro/faq/


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Yelp/yelp-api","title":"Yelp/yelp-api","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Yelp/yelp-api"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mittonk in #181: @xal629 : Looks like you're using the non-Yelp \"Yelp Widget Pro\":\r\n* https://wordpress.org/plugins/yelp-widget-pro/\r\n\r\nWe can't provide support for that 3rd party product --- please check out their FAQ, I suspect they want less data in the \"Business ID\" box:\r\n* https://wordpress.org/plugins/yelp-widget-pro/faq/\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/Yelp/yelp-api/issues/181#issuecomment-270024515"}}}

**Comment by mittonk** [comment]
There is no official Yelp widget for Wordpress.

**Comment by mittonk** [comment]
(For other readers looking to embed a single review: hover over a review on www.yelp.com and select "Embed Review" to get copy-pasteable HTML code.  Not a great match for this user's use case, though.)
