### ISSUE TITLE
Invalid Parameter

### ISSUE THREAD

**Issue by rahuls1** [Yelp/yelp-api#182]
Hi all,

I am trying to make a request with following api.

https://api.yelp.com/v2/search/?term=dinner&location=San Francisco, CA&limit=20&radius_filter=10000&oauth_consumer_key=anNmxVYyr4icE2usriqRhg&oauth_token=Mt6Wpv2N6DiUaBnIkuSV9oL0L0IetwsB&oauth_signature_method=HMAC-SHA1&oauth_signature=nirEvIvOl7d2L6PD9jvx9jKvTPQ&oauth_timestamp=1483452024&oauth_nonce=5

Bt giving Invalid Parameter.

{"error": {"text": "One or more parameters are invalid in request", "id": "INVALID_PARAMETER", "field": "oauth_token"}}

I am doing something wrong?

Thanks.

**Comment by tomelm** [comment]
Same as #183, closing.
