### ISSUE TITLE
Yelp API returns a missing parameter error

### ISSUE THREAD

**Issue by rahuls2704** [Yelp/yelp-api#183]
I try to retrieve some information from Yelp API for a UWP app. As they say here, I need to pass some parameter as header for a HTTP request, and then perform a Json request using this link. I know how to parse a Json file once I get it, but I have no idea how to get access to this file.

If for example I put https://api.yelp.com/v2/search?term=food&location=San+Francisco&oauth_signature_method=HMAC-SHA1&oauth_signature=nirEvIvOl7d2L6PD9jvx9jKvTPQ&oauth_timestamp=1483452024&oauth_nonce=5 this link on my browser

it return {"error": {"text": "One or more parameters are missing in request", "id": "MISSING_PARAMETER", "field": "oauth_consumer_key"}}

How should I enter this oauth_consumer_key?

**Comment by mittonk** [comment]
@rahuls2704 : Looks like you're trying the older V2 API; for new development, I'd suggest the newer Fusion (V3) API instead:
* https://www.yelp.com/developers/documentation/v3/get_started

The OAuth configuration in Fusion is much simpler and easier to use.

**Comment by rahuls1** [comment]
Thanks...
