### ISSUE TITLE
Example of /businesses/{id} for php

### ISSUE THREAD

**Issue by benrud** [Yelp/yelp-api#185]
Hello Everyone,

I'm a high school web design teacher and I'm trying to develop a project to teach my students how to use API's. This is my 1st attempt with them.

I'd like to learn how to request specific business information from yelp using the business endpoint (https://www.yelp.com/developers/documentation/v3/business) and echo specific data (rating and address) on the page using php. I've looked for examples online and asked on stackoverflow, but I haven't had any luck. 

Would someone be willing to build a quick example of a .php file that requests data using /businesses/{id} and echoes some of the data?

My students and I thank you. Have a great weekend,
Todd

**Comment by mittonk** [comment]
@benrud ,

We've got a separate Github area for the current Fusion (V3) API, check out 
* https://github.com/Yelp/yelp-fusion
and in particular the PHP example at
* https://github.com/Yelp/yelp-fusion/tree/master/fusion/php

That example does the hard part of calling the `api.yelp.com/v3/business/BUSINESS_ID` and printing the output --- have you done enough PHP to wire that into a simple hello-world webpage?

(This yelp-api area is for the older V2 API).

**Comment by benrud** [comment]
Hey Milton, 

Thanks for the directions and sorry for posting in the wrong place. I'll post this question over there. 

I've seen the https://github.com/Yelp/yelp-fusion/tree/master/fusion/php example and have it working here - http://foothillertech.com/student/webdesign/2016/02_benrud/tinker/data/ , but I'm trying to get a working example of the business endpoint (https://www.yelp.com/developers/documentation/v3/business) using php. I may be wrong, but I believe the example is over there is for the search  endpoint (https://www.yelp.com/developers/documentation/v3/business_search).   

Any chance you know of an example of the business endpoint working with php?

Thanks again and have a great weekend,
Todd

**Comment by mittonk** [comment]
Great, let's continue over in yelp-fusion#202 !

**Comment by benrud** [comment]
Thank you!
