### ISSUE TITLE
No total number in JSON result

### ISSUE THREAD

**Issue by francesco1119** [Yelp/yelp-api#186]
On this [page ](https://nz.yelp.com/developers/documentation/v3/get_started) on your documentation I can see a JSON query can return the total of the business in the very first line.

![total](https://cloud.githubusercontent.com/assets/3397477/26196385/ec573432-3c12-11e7-9411-40ec0ded61fc.PNG)

Why I don't have the same with Postman? 
I use exactly the same query as in your example

**Comment by mittonk** [comment]
@francesco1119 : Postman (like most JSON tools) doesn't always list the parts of the response in the same order.  Sometimes it lists `total` at the end:
```
      "phone": "+14153764747",
      "display_phone": "(415) 376-4747"
    }
  ],
  "total": 9
}
```

Could you look at the end of the output, and see if `total` is there?

**Comment by mittonk** [comment]
Also: this is a Fusion API (V3 API) question, so https://github.com/Yelp/yelp-fusion will be more helpful than https://github.com/Yelp/yelp-api (the old V2 API group).
