### ISSUE TITLE
How setup search by zip code

### ISSUE THREAD

**Issue by francesco1119** [Yelp/yelp-api#187]
I'm trying to retrieve cinemas by zip code so in the URL I set New Zealand as Country Code (`cc=NZ`) and Auckland city center zip code 1010 (`location=1010`)

`https://api.yelp.com/v3/businesses/search?cc=NZ&location=1010&categories=movietheaters`

Postman returns me 8 cinemas in Kentucky, USA :( 

So I also add "New Zealand" in the URL location for more accuracy (`location=New+Zealand+1010`)

`https://api.yelp.com/v3/businesses/search?cc=NZ&location=1010&categories=movietheaters`

Postman now returns me 13 cinemas from all over Auckland, not just the city center. :( 
My goal is to search businesses just in that specific zip code.

**Comment by mittonk** [comment]
@francesco1119 : Let's move this over to https://github.com/Yelp/yelp-fusion:
* https://github.com/Yelp/yelp-fusion/issues/233
