### ISSUE TITLE
Yelp blocked me from using their API 

### ISSUE THREAD

**Issue by Joyliu290** [Yelp/yelp-api#188]
Hi I'm programming an Android app that uses Yelp API Fusion 2 to output nearby restaurants. However I've noticed that Yelp has blocked my home wifi because of me testing my app and calling Yelp API, and now I can't even login to Yelp.com on my browser. Every wifi source I go to test my app, Yelp has blocked that wifi. I'm very frustrated because building app is my passion and I was a big fan of Yelp. I'm not making this app for illegal purposes, so I sincerely don't understand why Yelp has blocked me on every wifi address possible. Also, this is not fair for others who use/will use the wifi that I have used to test my app as their access to Yelp are blocked as well. 

Yelp is a big software company and it should encourage API usage from individual developer, not to block their access. Very disappointed.

**Comment by Joyliu290** [comment]
Feel free to look at my repository "Food Decision App" and tell me if I need to fix anything in relation to this issue. Otherwise I believe this issue has nothing to do with my code, but with Yelp itself blocking me for no apparent reason.

**Comment by tomelm** [comment]
Hey @Joyliu290, sorry you got blocked but sometimes it's an automatic action that our site takes and can be caused by a lot of things (like someone sharing an IP address and doing something malicious). Unfortunately I can't handle unblocking you but if you email api@yelp.com with your IP address they should be able to assist more.

**Comment by Joyliu290** [comment]
Hey @tomelm thanks for the reply, but no one in my house uses Yelp except for me, and I never done anything malicious other than using the Yelp's api. How likely would someone be able to reply to my email if I email api@yelp.com? I googled this a bit and people have said that Yelp rarely responds to email and phone calls...hence I'm posting this issue here on Github.

**Comment by tomelm** [comment]
It doesn't have to be someone in your house, IPs get recycled so it could be you got a new IP recently that was previously blocked. That's to say that that's what going on though, but that's possible.

api@yelp.com will respond to you for this issue, the alias is pretty responsive to issues like these. This repo is more focused on providing technical assistance on the API itself, IP blocks having on a more global level that's a little outside of our scope.

**Comment by Joyliu290** [comment]
Ok I see. Thank you!

**Comment by tomelm** [comment]
I saw they responded to you :D

If they stop responding let me know and I'll poke them.

**Comment by Joyliu290** [comment]
Hey sorry to bug you again but they have stopped responding for over a week now 👎 the issue is still not resolved :(

**Comment by Joyliu290** [comment]
Hey! Good news I'm now unblocked from Yelp! I was reading the display requirements more carefully and realized that I need to put the Yelp Logo on all content originated from Yelp...Is there a way for me to get access to the design of the Logo so I can put it on my app (making one myself is probably not the best option) ? Thanks!

**Comment by tomelm** [comment]
Awesome! That's all available on yelp.com/brand
