### ISSUE TITLE
No returns with integrated yelp search

### ISSUE THREAD

**Issue by MVEBA** [Yelp/yelp-api#192]
We have a yelp enabled and integrated on our website on real estate listing pages.  Hundreds of them.  There are no results regardless of how wide I open map.  I used a downtown location as a test
![capture2](https://user-images.githubusercontent.com/33497646/32572002-49490708-c497-11e7-84ec-e1b59f414554.PNG)
and no results.  Current token is iE1kRnOSkgWDOAdvYDoMm0bk1FrEq_t0 .  Is it possible it needs to be changed or refreshed?  How do I get a new code?

**Comment by mittonk** [comment]
@MVEBA : It'd helpful to see what request you're sending to the Yelp API, and what responses you're getting back --- that will show much more detail than the screenshot.

1. What is one example URL that isn't working?  Probably something like `https://api.yelp.com/v3/businesses/search?location=...`.  If you're not a developer, you might need a developer's help for this step.

2. If that URL has "v3" in it (likely): What is your Client ID from https://www.yelp.com/developers/v3/manage_app ?  Don't share your Client Secret.

3. If that URL has "v2" in it (less likely): What is your Consumer Key from https://www.yelp.com/developers/v2/manage_api_keys ?  Don't share your Consumer Secret.

4. What actual response are you getting from the API, both HTTP status code and response body?  There's usually an error message there that will help.

**Comment by MVEBA** [comment]
<div id="map_addons">
        <div id="toggle_links" class="clearfix">
            <div id="show_yelp" class="expanded">
              <a href="#" onclick="toggle_yelp();; return false;">Yelp Data<span></span></a>
            </div>
            <div id="show_directions" onclick="show_directions();">
              <a href="#" onclick="show_directions();; return false;">Get Directions<span></span></a>
            </div>
            <div id="hide_directions" style="display: none;">
              <a href="#" onclick="hide_directions(41.3972095, -70.530523); return false;">Hide directions<span></span></a>
            </div>
            <div id="toggle_street_view" class="last">
              <a href="#" onclick="void(0);; return false;">Street View<span></span></a>
            </div>
            <div id="toggle_street_view_off" class="last" style="display:none;">
              <a href="#" onclick="void(0);; return false;">Map View<span></span></a>
            </div>
        </div> 
        
          <div id="yelp_container" style="">
  <ul id="yelp_categories" class="clearfix">
      <li>
        <input id="yelp_" name="yelp_" style="display:none;" type="checkbox" value="1">
        <div id="" class=" yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_galleries" name="yelp_galleries" style="display:none;" type="checkbox" value="1">
        <div id="galleries" class="galleries yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_banks" name="yelp_banks" style="display:none;" type="checkbox" value="1">
        <div id="banks" class="banks yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_barbers" name="yelp_barbers" style="display:none;" type="checkbox" value="1">
        <div id="barbers" class="barbers yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_bars" name="yelp_bars" style="display:none;" type="checkbox" value="1">
        <div id="bars" class="bars yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_beaches" name="yelp_beaches" style="display:none;" type="checkbox" value="1">
        <div id="beaches" class="beaches yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_beer_and_wine" name="yelp_beer_and_wine" style="display:none;" type="checkbox" value="1">
        <div id="beer_and_wine" class="beer_and_wine yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_buildingsupplies" name="yelp_buildingsupplies" style="display:none;" type="checkbox" value="1">
        <div id="buildingsupplies" class="buildingsupplies yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_childcare" name="yelp_childcare" style="display:none;" type="checkbox" value="1">
        <div id="childcare" class="childcare yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_movietheaters" name="yelp_movietheaters" style="display:none;" type="checkbox" value="1">
        <div id="movietheaters" class="movietheaters yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_coffee" name="yelp_coffee" style="display:none;" type="checkbox" value="1">
        <div id="coffee" class="coffee yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_convenience" name="yelp_convenience" style="display:none;" type="checkbox" value="1">
        <div id="convenience" class="convenience yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_spas" name="yelp_spas" style="display:none;" type="checkbox" value="1">
        <div id="spas" class="spas yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_dentists" name="yelp_dentists" style="display:none;" type="checkbox" value="1">
        <div id="dentists" class="dentists yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_physicians" name="yelp_physicians" style="display:none;" type="checkbox" value="1">
        <div id="physicians" class="physicians yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_drugstores" name="yelp_drugstores" style="display:none;" type="checkbox" value="1">
        <div id="drugstores" class="drugstores yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_drycleaninglaundry" name="yelp_drycleaninglaundry" style="display:none;" type="checkbox" value="1">
        <div id="drycleaninglaundry" class="drycleaninglaundry yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_fitness" name="yelp_fitness" style="display:none;" type="checkbox" value="1">
        <div id="fitness" class="fitness yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_servicestations" name="yelp_servicestations" style="display:none;" type="checkbox" value="1">
        <div id="servicestations" class="servicestations yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_golf" name="yelp_golf" style="display:none;" type="checkbox" value="1">
        <div id="golf" class="golf yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_grocery" name="yelp_grocery" style="display:none;" type="checkbox" value="1">
        <div id="grocery" class="grocery yelp_list_icon selected"></div>
      </li>
      <li>
        <input id="yelp_hair" name="yelp_hair" style="display:none;" type="checkbox" value="1">
        <div id="hair" class="hair yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_homeandgarden" name="yelp_homeandgarden" style="display:none;" type="checkbox" value="1">
        <div id="homeandgarden" class="homeandgarden yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_hospitals" name="yelp_hospitals" style="display:none;" type="checkbox" value="1">
        <div id="hospitals" class="hospitals yelp_list_icon selected"></div>
      </li>
      <li>
        <input id="yelp_hotels" name="yelp_hotels" style="display:none;" type="checkbox" value="1">
        <div id="hotels" class="hotels yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_libraries" name="yelp_libraries" style="display:none;" type="checkbox" value="1">
        <div id="libraries" class="libraries yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_museums" name="yelp_museums" style="display:none;" type="checkbox" value="1">
        <div id="museums" class="museums yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_musicvenues" name="yelp_musicvenues" style="display:none;" type="checkbox" value="1">
        <div id="musicvenues" class="musicvenues yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_parks" name="yelp_parks" style="display:none;" type="checkbox" value="1">
        <div id="parks" class="parks yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_theater" name="yelp_theater" style="display:none;" type="checkbox" value="1">
        <div id="theater" class="theater yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_petservices" name="yelp_petservices" style="display:none;" type="checkbox" value="1">
        <div id="petservices" class="petservices yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_petstore" name="yelp_petstore" style="display:none;" type="checkbox" value="1">
        <div id="petstore" class="petstore yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_playgrounds" name="yelp_playgrounds" style="display:none;" type="checkbox" value="1">
        <div id="playgrounds" class="playgrounds yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_religiousorgs" name="yelp_religiousorgs" style="display:none;" type="checkbox" value="1">
        <div id="religiousorgs" class="religiousorgs yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_restaurants" name="yelp_restaurants" style="display:none;" type="checkbox" value="1">
        <div id="restaurants" class="restaurants yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_gourmet" name="yelp_gourmet" style="display:none;" type="checkbox" value="1">
        <div id="gourmet" class="gourmet yelp_list_icon"></div>
      </li>
      <li>
        <input id="yelp_vet" name="yelp_vet" style="display:none;" type="checkbox" value="1">
        <div id="vet" class="vet yelp_list_icon"></div>
      </li>
  </ul>
  
  <div id="yelp_data_lists">
      <div id="_list" class="category_list" style="display:none;"></div>
      <div id="galleries_list" class="category_list" style="display:none;"></div>
      <div id="banks_list" class="category_list" style="display:none;"></div>
      <div id="barbers_list" class="category_list" style="display:none;"></div>
      <div id="bars_list" class="category_list" style="display:none;"></div>
      <div id="beaches_list" class="category_list" style="display:none;"></div>
      <div id="beer_and_wine_list" class="category_list" style="display:none;"></div>
      <div id="buildingsupplies_list" class="category_list" style="display:none;"></div>
      <div id="childcare_list" class="category_list" style="display:none;"></div>
      <div id="movietheaters_list" class="category_list" style="display:none;"></div>
      <div id="coffee_list" class="category_list" style="display:none;"></div>
      <div id="convenience_list" class="category_list" style="display:none;"></div>
      <div id="spas_list" class="category_list" style="display:none;"></div>
      <div id="dentists_list" class="category_list" style="display:none;"></div>
      <div id="physicians_list" class="category_list" style="display:none;"></div>
      <div id="drugstores_list" class="category_list" style="display:none;"></div>
      <div id="drycleaninglaundry_list" class="category_list" style="display:none;"></div>
      <div id="fitness_list" class="category_list" style="display:none;"></div>
      <div id="servicestations_list" class="category_list" style="display:none;"></div>
      <div id="golf_list" class="category_list" style="display:none;"></div>
      <div id="grocery_list" class="category_list" style=""><h3>
  <a href="#" onclick="$('grocery_table').toggle();; return false;"><div class="grocery yelp_category_icon"></div>Grocery</a>
  <a class="reload" href="#" onclick="add_yelp_category($('yelp_grocery'), 'grocery');; return false;">Reload</a>
  <a class="yelp_clear" href="#" onclick="remove_yelp_category('grocery'); return false;">Clear</a>
</h3>

  <p>There is no data available.</p>
</div>
      <div id="hair_list" class="category_list" style="display:none;"></div>
      <div id="homeandgarden_list" class="category_list" style="display:none;"></div>
      <div id="hospitals_list" class="category_list" style=""><h3>
  <a href="#" onclick="$('hospitals_table').toggle();; return false;"><div class="hospitals yelp_category_icon"></div>Hospitals</a>
  <a class="reload" href="#" onclick="add_yelp_category($('yelp_hospitals'), 'hospitals');; return false;">Reload</a>
  <a class="yelp_clear" href="#" onclick="remove_yelp_category('hospitals'); return false;">Clear</a>
</h3>

  <p>There is no data available.</p>
</div>
      <div id="hotels_list" class="category_list" style="display:none;"></div>
      <div id="libraries_list" class="category_list" style="display:none;"></div>
      <div id="museums_list" class="category_list" style="display:none;"></div>
      <div id="musicvenues_list" class="category_list" style="display:none;"></div>
      <div id="parks_list" class="category_list" style="display:none;"></div>
      <div id="theater_list" class="category_list" style="display:none;"></div>
      <div id="petservices_list" class="category_list" style="display:none;"></div>
      <div id="petstore_list" class="category_list" style="display:none;"></div>
      <div id="playgrounds_list" class="category_list" style="display:none;"></div>
      <div id="religiousorgs_list" class="category_list" style="display:none;"></div>
      <div id="restaurants_list" class="category_list" style="display:none;"></div>
      <div id="gourmet_list" class="category_list" style="display:none;"></div>
      <div id="vet_list" class="category_list" style="display:none;"></div>
  </div>
</div>


        
        <div id="directions_fields" style="display:none;">
          <h5>Get Directions</h5>
          <div id="directions_form">
            <input type="hidden" id="initial_to_address" value="1 Oakdale Lane, Edgartown, MA 02539">
            <span>From: </span><input type="text" id="from_address">
            <div id="dir_reverse">
              <a href="javascript:void(0)">
                <img alt="Googlemap_icons_bg" class="arrows_reverse" src="http://blp-prodcdn1.scdn4.secure.raxcdn.com/assets/icons/googlemap_icons_bg-367d334ce87a21be2fb3eeeec085bece.png">
              </a>
            </div>
            <span>To: </span><input type="text" id="to_address" value="1 Oakdale Lane, Edgartown, MA 02539">
            <div id="travel_modes" class="clearfix">
              <strong>Choose a mode of transportation:</strong><br>
              <a href="javascript:void(0)" class="transportation_mode" data-transportation-mode="DRIVING" id="driving_directions"><img alt="Driving Directions" border="0" src="http://blp-prodcdn1.scdn4.secure.raxcdn.com/assets/icons/googlemap_icons_bg-367d334ce87a21be2fb3eeeec085bece.png"></a>
              <a href="javascript:void(0)" class="transportation_mode" data-transportation-mode="WALKING" id="walking_directions"><img alt="Walking Directions" border="0" src="http://blp-prodcdn1.scdn4.secure.raxcdn.com/assets/icons/googlemap_icons_bg-367d334ce87a21be2fb3eeeec085bece.png"></a>
              <a href="javascript:void(0)" class="transportation_mode" data-transportation-mode="BICYCLING" id="bicycling_directions"><img alt="Bicycling Directions" border="0" src="http://blp-prodcdn1.scdn4.secure.raxcdn.com/assets/icons/googlemap_icons_bg-367d334ce87a21be2fb3eeeec085bece.png"></a>
              <a href="javascript:void(0)" class="transportation_mode" data-transportation-mode="TRANSIT" id="public_directions"><img alt="Public Transit Directions" border="0" src="http://blp-prodcdn1.scdn4.secure.raxcdn.com/assets/icons/googlemap_icons_bg-367d334ce87a21be2fb3eeeec085bece.png"></a>
            </div>
            <div id="directionsPanel"></div>
          </div>
        </div> 
        
      </div> 
  </div>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>

**Comment by tomelm** [comment]
Sounds like everything is resolved, closing.

**Comment by mittonk** [comment]
Doesn't explain everything, but good enough for today!

**Comment by MVEBA** [comment]
Turns out had another error but guessing web host issue.  No alt tags on yelp buttons.  I tried searching deep into code but no luck finding api.yelp anywhere for request(?) and nothing but not sure my search goes deep into code.
