### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by aaduru** [Yelp/yelp-api#193]
Hi, 

I trying to make Get Request with Yelp api search endpoint in postman and I am getting validation error.

I am passing the 3 headers, term , location and authorization.

endpoint : https://api.yelp.com/v3/businesses/search

Header 
term: food
location: San Francisco
Authorization: Bearer [access_token] 

I even tried using the latitude and longitude in header section I am still getting the same error. 

term: food
location: 37.7749,122.4194
Authorization: Bearer [access_token] 
{
    "error": {
        "code": "VALIDATION_ERROR",
        "description": "Please specify a location or a latitude and longitude"
    }
}

Am i missing something here? 

Thank you.

**Comment by mittonk** [comment]
@aaduru : Term and location are parameters and go in the query string, not as headers:
URL: https://api.yelp.com/v3/businesses/search?term=food&location=San+Francisco
Header
Authorization: Bearer [access_token]

* https://www.yelp.com/developers/documentation/v3/business_search

Does that make sense?

**Comment by mittonk** [comment]
(Also, this Github repo is for the older V2 API --- in the future, you can post V3 Fusion questions at https://github.com/Yelp/yelp-fusion ).

**Comment by aaduru** [comment]
Thank you so much.
