### ISSUE TITLE
Posting responses to reviews using the Yelp API

### ISSUE THREAD

**Issue by Enny15** [Yelp/yelp-api#194]
Hello,

I just got introduced to the Yelp API and I was wondering if it's possible to post responses to reviews using the API.

Enny

**Comment by dan98765** [comment]
We are in the process of archiving this API v2 github repository, and as part of that are closing out all issues. 

---
Announcement:
As of June 30, 2018, the API v2 has been discontinued and v2 endpoints no longer work. It has been replaced by [Yelp's Fusion API](https://www.yelp.com/fusion). This github repository is archived. There is a new Yelp Fusion-specific github repository at https://github.com/Yelp/yelp-fusion.
