### ISSUE TITLE
how to integrate the yelp-fusion API

### ISSUE THREAD

**Issue by sriknthjanjirala1** [Yelp/yelp-api#196]
------------------------PHP------------------------
 i am downloaded the yelp api giving by below the link
https://github.com/Yelp/yelp-fusion

and register on 
https://www.yelp.com/developers/v3/manage_app   
for api key and get below keys
1) Client ID,
2) API Key ,
3) Client Secret,

when i run yelp api they generate the following error

Warning: assert(): NjHQysh2kED_pvhvYZuaCSm14T1aTBujPaa2z1ngQ0ADhw2CSrTQrmEgYpj3I4WDzbHGd03OJaQbNEGMwV0VeAbq3PAUtwW5UYq-Eldj5O4zseGpFfP1-awgSohdWnYx failed in C:\xampp\htdocs\yelp-fusion-master\fusion\php\sample.php on line 22

Notice: Undefined variable: API_KEY in C:\xampp\htdocs\yelp-fusion-master\fusion\php\sample.php on line 55

Fatal error: Curl failed with error #401: {"error": {"code": "TOKEN_MISSING", "description": "An access token must be supplied in order to use this endpoint."}} in C:\xampp\htdocs\yelp-fusion-master\fusion\php\sample.php on line 70

my code is,

<?php
/**
 * Yelp Fusion API code sample.
 *
 * This program demonstrates the capability of the Yelp Fusion API
 * by using the Business Search API to query for businesses by a 
 * search term and location, and the Business API to query additional 
 * information about the top result from the search query.
 * 
 * Please refer to http://www.yelp.com/developers/v3/documentation 
 * for the API documentation.
 * 
 * Sample usage of the program:
 * `php sample.php --term="dinner" --location="San Francisco, CA"`
 */
// API key placeholders that must be filled in by users.
// You can find it on
// https://www.yelp.com/developers/v3/manage_app
$API_KEY = NULL;
// Complain if credentials haven't been filled out.
assert($API_KEY, "----------------API KEY-------------------------");
// API constants, you shouldn't have to change these.
$API_HOST = "https://api.yelp.com";
$SEARCH_PATH = "/v3/businesses/search";
$BUSINESS_PATH = "/v3/businesses/";  // Business ID will come after slash.
// Defaults for our simple example.
$DEFAULT_TERM = "dinner";
$DEFAULT_LOCATION = "San Francisco, CA";
$SEARCH_LIMIT = 3;
/** 
 * Makes a request to the Yelp API and returns the response
 * 
 * @param    $host    The domain host of the API 
 * @param    $path    The path of the API after the domain.
 * @param    $url_params    Array of query-string parameters.
 * @return   The JSON response from the request      
 */
function request($host, $path, $url_params = array()) {
    // Send Yelp API Call
    try {
        $curl = curl_init();
        if (FALSE === $curl)
            throw new Exception('Failed to initialize');
        $url = $host . $path . "?" . http_build_query($url_params);
        curl_setopt_array($curl, array(
            CURLOPT_URL => $url,
            CURLOPT_RETURNTRANSFER => true,  // Capture response.
            CURLOPT_ENCODING => "",  // Accept gzip/deflate/whatever.
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "GET",
            CURLOPT_HTTPHEADER => array(
                "authorization: Bearer " . $API_KEY,
                "cache-control: no-cache",
            ),
        ));
        $response = curl_exec($curl);
        if (FALSE === $response)
            throw new Exception(curl_error($curl), curl_errno($curl));
        $http_status = curl_getinfo($curl, CURLINFO_HTTP_CODE);
        if (200 != $http_status)
            throw new Exception($response, $http_status);
        curl_close($curl);
    } catch(Exception $e) {
        trigger_error(sprintf(
            'Curl failed with error #%d: %s',
            $e->getCode(), $e->getMessage()),
            E_USER_ERROR);
    }
    return $response;
}
/**
 * Query the Search API by a search term and location 
 * 
 * @param    $term        The search term passed to the API 
 * @param    $location    The search location passed to the API 
 * @return   The JSON response from the request 
 */
function search($term, $location) {
    $url_params = array();
    
    $url_params['term'] = $term;
    $url_params['location'] = $location;
    $url_params['limit'] = $GLOBALS['SEARCH_LIMIT'];
    
    return request($GLOBALS['API_HOST'], $GLOBALS['SEARCH_PATH'], $url_params);
}
/**
 * Query the Business API by business_id
 * 
 * @param    $business_id    The ID of the business to query
 * @return   The JSON response from the request 
 */
function get_business($business_id) {
    $business_path = $GLOBALS['BUSINESS_PATH'] . urlencode($business_id);
    
    return request($GLOBALS['API_HOST'], $business_path);
}
/**
 * Queries the API by the input values from the user 
 * 
 * @param    $term        The search term to query
 * @param    $location    The location of the business to query
 */
function query_api($term, $location) {     
    $response = json_decode(search($term, $location));
    $business_id = $response->businesses[0]->id;
    
    print sprintf(
        "%d businesses found, querying business info for the top result \"%s\"\n\n",         
        count($response->businesses),
        $business_id
    );
    
    $response = get_business($business_id);
    
    print sprintf("Result for business \"%s\" found:\n", $business_id);
    $pretty_response = json_encode(json_decode($response), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    print "$pretty_response\n";
}
/**
 * User input is handled here 
 */
$longopts  = array(
    "term::",
    "location::",
);
    
$options = getopt("", $longopts);
$term = $options['term'] ?: $GLOBALS['DEFAULT_TERM'];
$location = $options['location'] ?: $GLOBALS['DEFAULT_LOCATION'];
query_api($term, $location);
?>

**Comment by tomelm** [comment]
Hey @sriknthjanjirala1!

First, please don't post your API key in the future. That's your personal key which grants you access the API, posting it publicly means that anyone will be able to use it on your behalf and use up your daily access limit. We're going to rotate your key for security reasons, you'll need to delete your app and create a new one.

Unfortunately the code you posted is really hard to read. It looks like you're using the sample from [here](https://github.com/Yelp/yelp-fusion/blob/master/fusion/php/sample.php). Based on what I can glean from the error messages, it looks like you're not setting the API key correctly. The PHP is throwing an assertion error where it validates the API key's existence and then the API itself returns a failure stating the API key is missing.

On line 22, could you confirm that your code looks something like
```
$API_KEY = "YOUR_API_KEY";
```

**Comment by sriknthjanjirala1** [comment]
thank you reply
 i am deleted the old app and created the new app
still i get a  same error
 i am using the given below code 
link :-     https://github.com/Yelp/yelp-fusion/blob/master/fusion/php/sample.php

and apply the API key in 
line number 25 :-     assert($API_KEY, "--------API KEY----------");
                                                             
please help me

**Comment by tomelm** [comment]
Hey @sriknthjanjirala1, you posted your api key again so we're going to disable that one, please be careful about posting them in the future.

We'll have someone on our side verify that the sample is working.

**Comment by virgytam** [comment]
Hi @sriknthjanjirala1, there is indeed a bug in the php sample code -- we aren't using the global $API_KEY and since it's not defined in the scope of the function, it's failing. I'll put out a fix for this.

**Comment by virgytam** [comment]
pull request on @teekwak https://github.com/Yelp/yelp-fusion/pull/385

**Comment by virgytam** [comment]
This is actually an issue on yelp-fusion, not yelp-api. This repo is for Public API V2 (just wanted to clarify)

The fix has been merged in for the V3/Fusion PHP sample
