### ISSUE TITLE
TOKEN_MISSING

### ISSUE THREAD

**Issue by ajhakeem** [Yelp/yelp-api#198]
I am using Yelp Fusion API for a native Android application, utilizing Retrofit for making requests. I have repeatedly ensured that I am passing my API_KEY as a header in a GET request in the below format:

"Authorization: Bearer <API_KEY>"

I even printed out the headers of ongoing requests, and they are exactly as I stated above. I can request and successfully retrieve results via curl and Postman, but not from Android. I have considered that it might be an issue regarding Retrofit, but I've found no mistakes in that. 

When I send the request, I get a 200 code and this error: 

> {"error": {"code": "TOKEN_MISSING", "description": "An access token must be supplied in order to use this endpoint."}}

I'm not sure where to turn at this moment, but can someone try pointing me in the right direction?

**Comment by dlgallagher** [comment]
Interesting. A couple questions that might help in debugging:

1. What is your client ID? (remember this is NOT the api key, which should never be posted publicly)
2. Could you please copy-paste in an excerpt of the headers you printed out for the Retrofit request (please redact any sensitive information, i.e. the api key)? 
3. What is the curl request you used to compare that against? (again, please redact any sensitive information, i.e. the api key)

**Comment by ajhakeem** [comment]
Firstly, sorry for posting in the wrong section!

1. My client ID is : ewYK-P0U1jzAtU-dGrm3bw
2. I am using an interceptor to modify the outgoing request with the headers. Note: I have also attempted to set headers both statically and dynamically. I have verified that the request definitely contains the headers because it correctly prints out 'Authorization: Bearer MY_API_KEY'.

`OkHttpClient.Builder okHttpBuilder = new OkHttpClient.Builder();

    okHttpBuilder.addInterceptor(new Interceptor() {
        @Override
        public okhttp3.Response intercept(Interceptor.Chain chain) throws IOException {
            Request original = chain.request();

            // Request customization: add request headers
            Request.Builder requestBuilder = original.newBuilder()
                    .addHeader("Authorization", "Bearer MY_API_KEY");
            Request request = requestBuilder.build();

            return chain.proceed(request);
        }
    });

    //Yelp Client init
    yelpRetrofit = new Retrofit.Builder()
            .baseUrl("https://api.yelp.com/v3/")    /*the rest of the endpoint is in a Retrofit client class*/
            .client(okHttpBuilder.build())
            .addConverterFactory(GsonConverterFactory.create())
            .build();
    yelpClient = yelpRetrofit.create(YelpClient.class);`


3. This is the curl request I sent

` curl -H "Authorization: Bearer MY_API_KEY" "https://api.yelp.com/v3/businesses/search?latitude=MY_LATITUDE&longitude=MY_LONGITUDE"`

**Comment by dan98765** [comment]
We are in the process of archiving this API v2 github repository, and as part of that are closing out all issues. 

---
Announcement:
As of June 30, 2018, the API v2 has been discontinued and v2 endpoints no longer work. It has been replaced by [Yelp's Fusion API](https://www.yelp.com/fusion). This github repository is archived. There is a new Yelp Fusion-specific github repository at https://github.com/Yelp/yelp-fusion.
