### ISSUE TITLE
python example fails with HTTP error 400

### ISSUE THREAD

**Issue by dennyglee** [Yelp/yelp-api#22]
When running the python example on OSX, I get the error: 
Encountered HTTP error 400. Abort program.

Digging in further, it appears that the issue is under def request when it is making the initial connection.

**Comment by bounaux** [comment]
hey guys, quick question on using the yelp api search by category example - i tested to query golf courses in seattle. when i set the max number of entries to return anything less than 20 i got valid response back, but when the max number of entries is changed to 21, i received http error 400 all the time - why is that?

**Comment by mittonk** [comment]
@bounaux : That looks unrelated, let's discuss that over in #48 .
