### ISSUE TITLE
C# implementation generates invalid signature, as it does not consider base string

### ISSUE THREAD

**Issue by iEchoic** [Yelp/yelp-api#29]
The C# implementation, when my key information is subbed in and ran, gives the following error:

REQUEST:
------------------------------------------------------------------------
GET http://api.yelp.com/v2/search/?term=thai&location=Seattle%252C%2520WA&limit=3 HTTP/1.1
Authorization: OAuth oauth_consumer_key="GzeIA9K2LG30d2zVM7FVow",oauth_nonce="b9c6e0f655e34e4782084457b0d82b07",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1404704198",oauth_token="oxiSh7zzELUi_dWMhLxeytbPcc5zF06w",oauth_version="1.0",oauth_signature="WpUFDczUNLM6u032WASz%2BpF9vlE%3D"
Host: api.yelp.com
Connection: Keep-Alive
------------------------------------------------------------------------

RESPONSE:
------------------------------------------------------------------------
HTTP/1.1 400 Bad Request
Date: Mon, 07 Jul 2014 03:36:35 GMT
Server: Apache
X-Node: web72-r7-sfo1, api_com
Cache-Control: private
Set-Cookie: bse=3462b728c385176c78cab0e1c8a67842; Domain=.yelp.com; Path=/; HttpOnly
Content-Length: 488
Vary: User-Agent
Content-Type: application/json; charset=UTF-8
X-Mode: rw
X-Proxied: lb1

{"error": {"text": "Signature was invalid", "id": "INVALID_SIGNATURE", "description": "Invalid signature. Expected signature base string: GET\u0026http%3A%2F%2Fapi.yelp.com%2Fv2%2Fsearch%2F\u0026limit%3D3%26location%3DSeattle%252C%2520WA%26oauth_consumer_key%3DGzeIA9K2LG30d2zVM7FVow%26oauth_nonce%3Db9c6e0f655e34e4782084457b0d82b07%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1404704198%26oauth_token%3DoxiSh7zzELUi_dWMhLxeytbPcc5zF06w%26oauth_version%3D1.0%26term%3Dthai"}}
------------------------------------------------------------------------

This appears to be because the C# app does not encode a base string - indeed, the response from the Yelp API seems to indicate this. This SO thread provides more information:

http://stackoverflow.com/questions/9330004/invalid-signature-for-signing-requests-to-the-flickr-api-simulation-in-console

Is there a working implementation floating around or should I hack around with this one?

**Comment by mittonk** [comment]
OK, got a Windows box up and running to debug.
Visual Studio 2013 and .NET 4.0 work as expected.

Trying some other versions...

**Comment by mittonk** [comment]
Visual Studio 2013 and .NET 4.5.1 works as expected.  @iEchoic  --- I'd love to compare to your setup, see why you can reproduce this issue and I can't.

**Comment by fiza89** [comment]
im facing the same issue...is there any solution??

**Comment by mittonk** [comment]
@fiza89 , what version of Visual Studio and .NET are you using?

**Comment by mittonk** [comment]
Repro'd an HTTP 400 error using VS 2013 Community, .NET 4.0, and stale version of these examples: 9ee4692.

Rolled forward to c94870a, got an HTTP 400 with this error message.

Rolled forward again to pick up the #43 fix, get the expected results (HTTP 200, with some nice JSON).

So, I'm going to say #43 fixes this.

@fiza89 , @iEchoic , et al: Please make sure your version of yelp-api contains commit 23dab14 !  If you're not sure, download a fresh copy from Github.

**Comment by fiza89** [comment]
its working fine now.... but sometimes it returns invalid signature and sometimes the correct result.
What could be the issue.??
