### ISSUE TITLE
ARC

### ISSUE THREAD

**Issue by dsestes** [Yelp/yelp-api#32]
Is there a quick way to implement this in a project that uses ARC? I pasted it into my app, and got 41 issues related to ARC because the code is full of retain / release / auto retain.

**Comment by MatthewHendy** [comment]
in my build settings the 'Objective-C Automatic Reference Counting' flag is set to yes yet i have 94 errors relating to 'release' , 'autorelease' , ARC restrictions, and ARC casting rules

**Comment by mittonk** [comment]
Hm, interesting.
