### ISSUE TITLE
Python sample fails when business ID contains special characters

### ISSUE THREAD

**Issue by tathougies** [Yelp/yelp-api#33]
Hello!

Using the Search API python sample to search for restaurants sometimes fails with the error:

Traceback (most recent call last):
  File "search-yelp.py", line 170, in <module>
    main()
  File "search-yelp.py", line 164, in main
    query_api(input_values.term, input_values.location)
  File "search-yelp.py", line 149, in query_api
    response = get_business(business)
  File "search-yelp.py", line 119, in get_business
    return request(API_HOST, business_path)
  File "search-yelp.py", line 63, in request
    url = 'http://{0}{1}?{2}'.format(host, path, encoded_params.encode('utf8'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 16: ordinal not in range(128)

This happens because business IDs can contain special characters like "é", which cannot be put into URLs before being decoded. For example, in this instance the specific cause of failure is trying to access the API endpoint "/v2/business/café-pro-bono-palo-alto-3".

This is easily fixed by changing line 59 to:

url = 'http://{0}{1}?{2}'.format(host, urllib.urlencode(path), encoded_params)

**Comment by lechatpito** [comment]
This change is still not updated in the example.

**Comment by mittonk** [comment]
Taking a look.

**Comment by mittonk** [comment]
Reproduced using
```python
DEFAULT_TERM = 'cafe pro bono'
```
Newer stacktrace is:
```python
Querying http://api.yelp.com/v2/search/? ...
Traceback (most recent call last):
  File "sample.py", line 158, in <module>
    main()
  File "sample.py", line 152, in main
    query_api(input_values.term, input_values.location)
  File "sample.py", line 134, in query_api
    business_id
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 3: ordinal not in range(128)
```
Whipping up a slightly-larger version of @tathougies fix.
