### ISSUE TITLE
C# API returns HTTP 400 error

### ISSUE THREAD

**Issue by Antrikshy** [Yelp/yelp-api#35]
I just downloaded, extracted the folder, built the API and ran the exe file as described, with similar arguments, and it does not work. Is there another setup step needed or is the library not working for some reason?

I'm new to C#.

**Comment by mittonk** [comment]
OK, got a Windows box up and running to debug.
Visual Studio 2013 and .NET 4.0 work as expected.

Trying some other versions...

**Comment by mittonk** [comment]
Visual Studio 2013 and .NET 4.5.1 works as expected.  @pvanroos --- I'd love to compare to your setup, see why you can reproduce this issue and I can't.

**Comment by pvanroos** [comment]
Sorry Ken.   Let me test today.

**Comment by mittonk** [comment]
@pvanroos : Actually, that's pretty good news to me; that indicates this might just be a different error message around #30 / #43 .

I'll see if I can confirm with a version of master before that fix.

**Comment by mittonk** [comment]
@pvanroos : Great, was able to repro the failure by checking out a version without the #43 commits, with Visual Studio 2013 Community and .NET 4.0.

Rolling forward to get that commit resolved the issue.

So, I'll say #43 resolves this issue.  Thanks for the check, that helped!
