### ISSUE TITLE
Objective-c sample code does not working (auth failed, err code: 403)

### ISSUE THREAD

**Issue by KaBlaize** [Yelp/yelp-api#37]
Hi,
The objective-c sample code does not working with API v2.
And some of other people reported the API authentication stop working on 18th Aug.
See https://groups.google.com/forum/#!topic/yelp-developer-support/WmcSouYmjso
The returned message only a standard 403 message from the server as you can see in the linked forum topic.

Please fix this issue.

**Comment by mittonk** [comment]
Works fine for me now, please open a fresh issue if you hit more problems.
