### ISSUE TITLE
Time for version 1.0

### ISSUE THREAD

**Issue by AhmedSamy** [Yelp/yelp-api#47]
it's time to create release tag on GitHub for proper dependency management

**Comment by tomelm** [comment]
As it stands, I'm not sure that versioning this repo makes a ton of sense. We'd have to do version bumps for a lot of unrelated changes and following the changes and relevant versions would get complicated.

As we have time I'm imagining splitting this out would be better, but in the meantime I don't see versioning this repo as a good idea. @mittonk let me know what you think.

**Comment by mittonk** [comment]
I'd agree --- let's version separate single-language repos as we create them.
