### ISSUE TITLE
Updating search term language

### ISSUE THREAD

**Issue by davejohn** [Yelp/yelp-api#48]
I think it would be helpful to update [the documentation](http://www.yelp.com/developers/documentation/v2/search_api) to clarify that the `term` in the search parameters can be fed the name of the restaurant you're looking for. This saved me a lot of time once I realized it takes more than generic terms like "dinner" etc.

Just a suggestion, thanks for the great work!

![](http://i.imgur.com/LAvJUkC.png)

**Comment by tomelm** [comment]
Thanks for the suggestion! We'll update the documentation to make it clearer

**Comment by mittonk** [comment]
At a high level: This works roughly like the search-term box on the Yelp website or mobile app;  you can also search for "Joe's Diner", "cheap ham and cheese sandwich", etc.

**Comment by mittonk** [comment]
@bounaux wrote in mostly-unrelated #22 :
>hey guys, quick question on using the yelp api search by category example - i tested to query golf courses in seattle. when i set the max number of entries to return anything less than 20 i got valid response back, but when the max number of entries is changed to 21, i received http error 400 all the time - why is that?

Search returns at most 20 results per request, might be worth clarifying that as well.
http://www.yelp.com/developers/documentation/v2/search_api

**Comment by mittonk** [comment]
@tomelm , you had some ideas on new language; tossing you this.

**Comment by tomelm** [comment]
This is [finally] done
