### ISSUE TITLE
PHP Example throws INVALID_OAUTH_CREDENTIALS

### ISSUE THREAD

**Issue by jamesaspence** [Yelp/yelp-api#54]
When running sample.php inside terminal, I get the following code:
stdClass Object
(
    [error] => stdClass Object
        (
            [text] => The OAuth credentials are invalid
            [id] => INVALID_OAUTH_CREDENTIALS
        )

)

Anything to be done to fix this? I'm struggling to implement this API in a current project.

**Comment by virgytam** [comment]
Hi James, are you running example.php without editting the oauth credentials? By default, those are blanked out

`// Set your OAuth credentials here`
`// These credentials can be obtained from the 'Manage API Access' page in the`
`// developers documentation (http://www.yelp.com/developers)`
`$CONSUMER_KEY = NULL;`
`$CONSUMER_SECRET = NULL;`
`$TOKEN = NULL;`
`$TOKEN_SECRET = NULL;`

and you need to populate these fields with your credentials that you can find here: http://www.yelp.com/developers/manage_api_keys

**Comment by jamesaspence** [comment]
That was part of the issue. I got the example code working. However, in my own adaptation of the code, I'm getting an INVALID_SIGNATURE error. I'm assuming I encrypted the string wrong somehow, but I'm not sure how, since I'm using the exact code provided.

```
$token = new OAuthToken($service->token, $service->tokenSecret);
$consumer = new OAuthConsumer($service->consumerKey, $service->consumerSecret);

$signatureMethod = new OAuthSignatureMethod_HMAC_SHA1();

$request = OAuthRequest::from_consumer_and_token($consumer, $token, 'GET', $url);

$request->sign_request($signatureMethod, $consumer, $token);

$signedUrl = $request->to_url() . http_build_query($params);
$ch = curl_init($signedUrl);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HEADER, 0);
$data = curl_exec($ch);
curl_close($ch);
print_r($data);exit;
```

returns:

```
{
    "text": "Signature was invalid", 
    "id": "INVALID_SIGNATURE", 
    "description": "OAuth version 1.0term=dinner not supported."}}
```

**Comment by virgytam** [comment]
What does $signedUrl look like? It looks like when you append http_build_query($params) to the url, it may not be added that '&' between the oauth params and the query params. 

In the code sample, the query params are appended to the api url before the entire url is signed so that might fix the issue.

**Comment by jamesaspence** [comment]
Could you give me an example of what that might look like?

Here's $signedUrl(with creds replaced with <> brackets):
`GET&http%3A%2F%2Fapi.yelp.com%2Fv2%2Fsearch&oauth_consumer_key%3D<CONSUMER_KEY>%26oauth_nonce%3D<NONCE>%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1424205944%26oauth_token%3D<TOKEN>%26oauth_version%3D1.0http://api.yelp.com/v2/search?oauth_consumer_key=<CONSUMER_KEY>&oauth_nonce=<NONCE>&oauth_signature=zTEM1PAK70GoFIkN278qZedDkW8%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1424205944&oauth_token=<TOKEN>&oauth_version=1.0&0=-n+%27Motor+Bar+%26+Restaurant%27&1=-c+%27Milwaukee%27&2=-s+%27WI%27`

**Comment by jamesaspence** [comment]
To give you more information, the consumer key, nonce, etc. appear to be hashed in the first part (i.e. up until `%3D1.0http://api.yelp.com/v2/`, and after that are just plain string. So I don't encode that second part of credentials

**Comment by jamesaspence** [comment]
NEVERMIND! I got it! I had screwed it up somewhere along the line. I had added the parameters at the end of the signed url for some weird reason accidentally. So it was throwing an error. Got it working now, thanks.
