### ISSUE TITLE
Convert all examples to use HTTPS

### ISSUE THREAD

**Issue by mittonk** [Yelp/yelp-api#55]
SSL is good.  Keeps private stuff private.

The Yelp API is available using https, but not all examples use it all the time.  They should!

A few obvious flags:
```
$ ack -a 'http://api'
v2/csharp/YelpAPI/Program.cs
59:        private const string API_HOST = "http://api.yelp.com";

v2/perl/search.pl
18:sub user_url { 'http://api.yelp.com/v2/search?term=food&location=San+Francisco' }

v1/googlemaps_example/businessSearch.html
60:        var URL = "http://api.yelp.com/" +
```

We should audit the examples, find any that use plain http, and upgrade them to https.

**Comment by mittonk** [comment]
C# example works on https without other modifications, good.

Perl example complains:
```
500 Can't verify SSL peers without knowing which Certificate Authorities to trust
Content-Type: text/plain
Client-Date: Sun, 05 Apr 2015 03:57:24 GMT
Client-Warning: Internal response

Can't verify SSL peers without knowing which Certificate Authorities to trust

This problem can be fixed by either setting the PERL_LWP_SSL_CA_FILE
envirionment variable or by installing the Mozilla::CA module.

To disable verification of SSL peers set the PERL_LWP_SSL_VERIFY_HOSTNAME
envirionment variable to 0.  If you do this you can't be sure that you
communicate with the expected peer.
Something went wrong at search.pl line 42.
```
Installing `Mozilla::CA` did the trick, but does raise the bar of entry a little.  @tomelm , any opinions?

**Comment by tomelm** [comment]
I don't think it's too bad having that ``Mozilla::CA`` dependency. If all you need to do is install it I think it should be okay!

**Comment by mittonk** [comment]
Great, I'll go that direction.

**Comment by mittonk** [comment]
OK, all the documentation now says HTTPS; now's a good time to update the examples.

Looking at `Mozilla::CA`.
