### ISSUE TITLE
PHP phone search

### ISSUE THREAD

**Issue by txt3rob** [Yelp/yelp-api#56]
PHP phone does not search via the phone number

the below should resolve that for uk numbers

```
$API_HOST = 'api.yelp.com';
$DEFAULT_TERM = '';
$DEFAULT_LOCATION = 'GB';
$SEARCH_PHONEPATH = '/v2/phone_search';

function search_phone($term, $location) {
    $url_params = array();
    
    $url_params['phone'] = $term ?: $GLOBALS['DEFAULT_TERM'];
    $url_params['cc'] = $location?: $GLOBALS['DEFAULT_LOCATION'];
    $search_path = $GLOBALS['SEARCH_PHONEPATH'] . "?" . http_build_query($url_params);
    return request($GLOBALS['API_HOST'], $search_path);
}
```

**Comment by virgytam** [comment]
Hi Robbie, what does your final query string look like? Also, what response are you getting? 

Here's a quick example of what the phone and cc params would look like for Great Queen Street in London: 

http://api.yelp.com/v2/phone_search/?cc=GB&phone=%2B44+20+7242+0622

**Comment by mittonk** [comment]
@txt3rob : Sounds like you're trying to contribute example code for v2 Phone Search, to be added to `v2/php/sample.php`.  Is that right?

Code looks pretty good, a comment documenting the inputs might be a good addition.

I'd probably call the first input `$phone` rather than `$term` for clarity, but that's more personal preference.

**Comment by txt3rob** [comment]
sorry it was a bit of code to be submitted as an example for the phone search as the example code provided does not show this and i had to work it out.

I get results from this just fine.

**Comment by tomelm** [comment]
@txt3rob if you wanted to create a pull request with what you want to add we can go from there!

**Comment by mittonk** [comment]
(These examples are meant to demonstrate a few basic flows, and don't cover every endpoint or argument --- that's better done in a dedicated clientlib like https://github.com/Yelp/yelp-python.  

However, we don't have a PHP clientlib yet, so I don't have any major objection.)

**Comment by watterso** [comment]
(sorry everyone for reviving a long dead thread, just adding a note before closing.)

To reiterate what was said above, the samples are used to help get people started, if you want this phone search example to be part of the sample, please create a pull request and we will review it there.
