### ISSUE TITLE
the node js API library returns "One or more parameter is missing: oauth_consumer_key"

### ISSUE THREAD

**Issue by franklingu** [Yelp/yelp-api#58]
as title

**Comment by mittonk** [comment]
Hm, I remember this working last time I ran it.

@franklingu : Have you already filled in your own `oauth_consumer_key` value into the example script?

**Comment by franklingu** [comment]
Yes, the default node oauth actually puts those info in header but I think
yelp requires them as parameter in url




Gu Junchao
Major in Computer Engineering, National University of Singapore
Primary Email: *franklingujunchao@gmail.com <franklingujunchao@gmail.com>*
NUS Email: *A0105750@ <A0105750@nus.edu.sg>u.nus.edu <http://u.nus.edu>*

**Comment by mittonk** [comment]
OK, looks like the Node.js example is actually part of a separate repo, https://github.com/olalonde/node-yelp .  Poking.

**Comment by franklingu** [comment]
well, that is actually reported by me too ;P

**Comment by mittonk** [comment]
@franklingu : That's a pretty snazzy blog post.

Debugging over in https://github.com/olalonde/node-yelp/issues/8 , closing this as a duplicate.

**Comment by mittonk** [comment]
Duplicate of https://github.com/olalonde/node-yelp/issues/8 , debugging over there.
