### ISSUE TITLE
run.sh script for that java example silently fails when run on windows

### ISSUE THREAD

**Issue by maltzj** [Yelp/yelp-api#62]
I was working with a windows user at a hackathon today and he tried to follow the directions on the readme only to get a silent failure.

Maybe we should include a .bat script for windows folks?

**Comment by mittonk** [comment]
Sounds like you're talking about the Java example, `v2/java/run.sh`.  Sounds like a plan.

**Comment by maltzj** [comment]
Yup.  Thanks for understanding my 2 AM tickets :)

**Comment by mittonk** [comment]
`run.sh` is pretty simple; no `Makefile`, `maven`, `ant`, or other dependency management.

So, a 3-line `.bat` seems like a fine Windows version.

Time to go spin up my Windows box.
