### ISSUE TITLE
"Expired timestamp: given 1444301292 and now 1444301624 has a greater difference than threshold 300

### ISSUE THREAD

**Issue by sachintaware** [Yelp/yelp-api#65]
I have verified the time on the server and that is correct. How to resolve or debug this error?
This works on the local machine but fails on server. It worked till recent time,but started failing without reason.

**Comment by mittonk** [comment]
@sachintaware , 
Hm, let's see what we can figure out.

1. What timezone do your server & local machine think they're in?  "date" on each machine will show that:
```
$ date
Thu Oct  8 06:25:14 PDT 2015
```
2. What language are you using (Python, PHP, etc)?

3. Does this affect the simple example scripts, or just your full application?

**Comment by sachintaware** [comment]
Hello our servers are in US east time zone. We are using PHP. I am accessing it from India which is GMT+5:30. It works when I send a request from local,but fails on server.

**Comment by mittonk** [comment]
@sachintaware : 

Hm, this is ~7 minutes different.  That sounds like either a long-running process, or server time skew.

1. Could you try using the PHP example, with no modifications other than adding your OAuth info?   I want to rule out any delays in a long script that hits the Yelp API as one of several activities.

2. Are you running NTPd or a similar thing to keep your server's clock up-to-date?  Server clock skew could explain this 7-minute difference, and wouldn't necessarily cause the same problems for all social APIs.

**Comment by sachintaware** [comment]
Sorry for the delayed response,I was away for the time.I will try it out.Also,I had some server side issue with Laravel,which might have caused the error. I will test and update with my results. 
@mittonk

**Comment by sachintaware** [comment]
@mittonk I believe there was a server side issue which prolonged the request and hence the error.I had to update the server size at it ws out of space.Once I did that the issue was resolved. I will keep the issue open for the next 24hrs,in case I face it again,if not I will close the thread. Thank you for the inputs.

**Comment by mittonk** [comment]
Wonderful, that would indeed explain what we saw here.

**Comment by sachintaware** [comment]
@mittonk yes that was the issue,a server overload due to size limit prolonged the request. Thank you for the help and inputs. Cheers
