### ISSUE TITLE
Category lists outdated

### ISSUE THREAD

**Issue by tomelm** [Yelp/yelp-api#68]
I think we should remove the folder, it hasn't been updated in 4 years and we have a JSON dump here: https://www.yelp.com/developers/documentation/v2/all_category_list

@mittonk thoughts?

**Comment by mittonk** [comment]
Yep, my plan is to remove this directory and supply a direct link to the JSON dump on that page.  (That download URL is still in some flux).

(I also half-remember this being a code dependency for something, tracking that down.)

**Comment by mittonk** [comment]
Dup of #14 .
