### ISSUE TITLE
Python file should have UTF-8 coding pragma

### ISSUE THREAD

**Issue by mittonk** [Yelp/yelp-api#77]
Maybe also some PEP8 newlines between functions.

**Comment by tomelm** [comment]
@mittonk thoughts on going all the way and adding [pre-commit](http://pre-commit.com/)?

**Comment by dlgallagher** [comment]
I'm a big fan of adding pre-commit

**Comment by mittonk** [comment]
I am too --- but that's a bigger change so we can do it separately as #78.

**Comment by mittonk** [comment]
Huh, we've already got a coding pragma:
```
 -*- coding: utf-8 -*-
```
Was I looking at a stale branch?
