### ISSUE TITLE
Update Python example code in view of yelp-python clientlib

### ISSUE THREAD

**Issue by mittonk** [Yelp/yelp-api#81]
https://github.com/Yelp/yelp-python is much more flexible than our little Python `sample.py`.
Should the Python example:
1. Go away entirely, and just point to the clientlib?
2. Demonstrate how to use the clientlib?
3. Turn into an extra-repo example of how to use the clientlib, sort of like https://github.com/Yelp/yelp-rails-example ?

**Comment by tomelm** [comment]
My opinions:
1. Yes
2. No, readme should cover that
3. Possibly but I'm not sure it's necessary. I did that as a hackathon project, I don't know if there's a lot of value in it.

**Comment by mittonk** [comment]
Seems reasonable.  Let's leave some overlap time with both a link to the clientlib and the sample code, then send everyone over to the clientlib.

**Comment by mittonk** [comment]
When doing this, either handle `/v2/java` as well or kick off a separate ticket to wait a while and deal with it.

**Comment by tomelm** [comment]
I'm going to open a PR to remove the Python sample since it looks like it's causing some confusion

**Comment by mittonk** [comment]
(Rolled back in #113 because this broke some links, we can roll forward once those are updated.)

**Comment by watterso** [comment]
Re-removed in #114
