### ISSUE TITLE
Expired timestamp

### ISSUE THREAD

**Issue by tbass134** [Yelp/yelp-api#9]
on IOS 4.2.1, the response for the yelp data is 

{
  "error": {
    "text": "Signature was invalid",
    "id": "INVALID_SIGNATURE",
    "description": "Expired timestamp: given 1326837029 and now 1326841425 has a greater difference than threshold 300"
  }
}

on an IOS 5 device, running the same code, everything is fine.

**Comment by resourcemode** [comment]
Encounter same issue on my web app. Any solution?
