### ISSUE TITLE
Could you provide more information in the API?

### ISSUE THREAD

**Issue by KaiWangCanada** [Yelp/yelp-api#91]
Hi Yelp, 

I am using Yelp API in an Android App, it works great. The only problem is, it only provides few images and reviews of a business. I want to get all the images and reviews, can you provide these information? Just want to know, thank you!

**Comment by tomelm** [comment]
Hey @KaiWangCanada! Could you email api@yelp.com with this request? They may be able to help

**Comment by KaiWangCanada** [comment]
Thank you, Tomelm.
