### ISSUE TITLE
Question about what we can do with Yelp API

### ISSUE THREAD

**Issue by Soco45** [Yelp/yelp-api#94]
Hi there,

I have little/no programming experience so please excuse my non-technical language, or if I posted this in the wrong place.

I am looking for a way to search Yelp for businesses that are closed.  I don't see a way to do this at Yelp.com, but is this something that can be done through the Yelp API - if I hire someone to write a custom program?

Thanks,

Mike

**Comment by mittonk** [comment]
@Soco45 ,

Searches via
* https://www.yelp.com/developers/documentation/v2/search_api
might return some closed businesses (`is_closed: true`), but you can't specify that you're looking only for closed businesses.
