### ISSUE TITLE
Yelp Deals

### ISSUE THREAD

**Issue by bkauyeung** [Yelp/yelp-api#96]
Hi, I'm not sure how the yelp deals option works. It says that it takes a boolean value. I'm using python - I entered in a value of "1" and "true" different times, expecting the api to give me a business with a yelp deal. It didn't. It keeps returning the same business. I'm not sure whats going on... Also - the result never just tells me if the business has a deal or not - the only way I figured it out was because the it said that the business wasn't claimed. Hence, deals are not possible. Someone help me!!!

**Comment by mittonk** [comment]
@bkauyeung , what's your example request (api.yelp.com/v2/search....deals_filter=.... )?

https://api.yelp.com/v2/search/?location=San Francisco, CA&deals_filter=true
gives good results for me:
```
{
    "region": {
        "span": {
            "latitude_delta": 0.0, 
            "longitude_delta": 0.0
        }, 
        "center": {
            "latitude": 37.7919608, 
            "longitude": -122.3964885
        }
    }, 
    "total": 2067, 
    "businesses": [
        {
            "is_claimed": true, 
            "rating": 5.0, 
            "mobile_url": "http://m.yelp.com/biz/elixiria-san-francisco?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=sWc_ig2aihT0s-6Yf-zGIQ", 
            "rating_img_url": "http://s3-media1.fl.yelpcdn.com/assets/2/www/img/f1def11e4e79/ico/stars/v1/stars_5.png", 
            "review_count": 47, 
            "name": "Elixiria", 
            "rating_img_url_small": "http://s3-media1.fl.yelpcdn.com/assets/2/www/img/c7623205d5cd/ico/stars/v1/stars_small_5.png", 
            "url": "http://www.yelp.com/biz/elixiria-san-francisco?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=sWc_ig2aihT0s-6Yf-zGIQ", 
            "categories": [
                [
                    "Juice Bars & Smoothies", 
                    "juicebars"
                ], 
                [
                    "Gluten-Free", 
                    "gluten_free"
                ], 
                [
                    "Vegan", 
                    "vegan"
                ]
            ], 
            "menu_date_updated": 1453800938, 
            "deals": [
                {
                    "is_popular": true, 
                    "what_you_get": "You get a voucher redeemable for $30 at Elixiria.\nPrint out your voucher, or redeem on your phone with the <a href=\"http://www.yelp.com/mobile?source=deal_marketing\">Yelp app</a>.", 
                    "time_start": 1452697246, 
                    "title": "$25 for $30", 
                    "url": "http://www.yelp.com/deals/elixiria-san-francisco-3?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=sWc_ig2aihT0s-6Yf-zGIQ", 
                    "additional_restrictions": "Promotion lasts for 1 year from date of purchase. After that period, your voucher is redeemable for the amount you paid, less any value you may have received. Not valid with other vouchers, certificates, or offers. Only 1 voucher(s) can be purchased and redeemed per person. Up to 1 can be purchased as gifts for others. Subject to the <a target=\"_blank\" href=\"http://www.yelp.com/tos/general_b2c_us_20120911\">General Terms</a>.", 
                    "options": [
                        {
                            "original_price": 3000, 
                            "title": "$25 for $30", 
                            "price": 2500, 
                            "purchase_url": "https://www.yelp.com/checkout/deal/9U-Ov0aKp2WNbTpO29Eolw?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=sWc_ig2aihT0s-6Yf-zGIQ", 
                            "remaining_count": 19, 
                            "formatted_original_price": "$30", 
                            "formatted_price": "$25", 
                            "is_quantity_limited": true
                        }
                    ], 
                    "important_restrictions": "Limit 1 voucher(s) per table.", 
                    "image_url": "http://s3-media1.fl.yelpcdn.com/dphoto/QgZP3XYkpZKXZex21UsZdA/m.jpg", 
                    "id": "gCVnQjTG1GNF6r4wRx4jDg", 
                    "currency_code": "USD"
                }
            ], 
            "phone": "6284443149", 
            "snippet_text": "I still give 5 stars for Elixiria.  After coming here many times after work, I've noticed this juice bar have some locally raised meat and veggie lunch...", 
            "image_url": "http://s3-media4.fl.yelpcdn.com/bphoto/Vs1cl8ZO9WM9JqmcrHXXaQ/ms.jpg", 
            "snippet_image_url": "http://s3-media3.fl.yelpcdn.com/photo/P_53JYc6-sJTFqyMDWTU3Q/ms.jpg", 
            "display_phone": "+1-628-444-3149", 
            "rating_img_url_large": "http://s3-media3.fl.yelpcdn.com/assets/2/www/img/22affc4e6c38/ico/stars/v1/stars_large_5.png", 
            "menu_provider": "eat24", 
            "id": "elixiria-san-francisco", 
            "is_closed": false, 
            "location": {
                "cross_streets": "Davis St & Market St", 
                "city": "San Francisco", 
                "display_address": [
                    "25 Beale St", 
                    "Unit 2", 
                    "Financial District", 
                    "San Francisco, CA 94105"
                ], 
                "geo_accuracy": 8.0, 
                "neighborhoods": [
                    "Financial District", 
                    "SoMa"
                ], 
                "postal_code": "94105", 
                "country_code": "US", 
                "address": [
                    "25 Beale St", 
                    "Unit 2"
                ], 
                "coordinate": {
                    "latitude": 37.792199626565, 
                    "longitude": -122.39696636796
                }, 
                "state_code": "CA"
            }
        }
    ]
...
```

https://www.yelp.com/developers/api_console can help demo some of the parameters.

**Comment by bkauyeung** [comment]
That makes sense to me when I put it into the api console, but for some reason - my code is not running even when i set the deals_filter = true! 
When I run it through the python console (after altering the sample code to include deals_filter and offset, etc), it doesnt give me what the api console shoots out!

**Comment by watterso** [comment]
@bkauyeung could you give us a sample of what you are running (**without** your credentials) ? Might help us debug this better.

**Comment by bkauyeung** [comment]
How do I attach a py file? Its not letting me do it here

**Comment by bkauyeung** [comment]
`API_HOST = 'api.yelp.com'
DEFAULT_TERM = ''
DEFAULT_LOCATION = 'San Francisco, CA'
DEFAULT_OFFSET = 0
DEFAULT_SORT = 2
DEFAULT_CATEGORY_FILTER = ''
DEFAULT_DEALS_FILTER = 1
SEARCH_LIMIT = 1
SEARCH_PATH = '/v2/search/' 
BUSINESS_PATH = '/v2/business/'

# OAuth credential placeholders that must be filled in by users.
CONSUMER_KEY = ""
CONSUMER_SECRET = ""
TOKEN = ""
TOKEN_SECRET = ""

def request(host, path, url_params=None):
    """Prepares OAuth authentication and sends the request to the API.

    Args:
        host (str): The domain host of the API.
        path (str): The path of the API after the domain.
        url_params (dict): An optional set of query parameters in the request.

    Returns:
        dict: The JSON response from the request.

    Raises:
        urllib2.HTTPError: An error occurs from the HTTP request.
    """
    url_params = url_params or {}
    url = 'https://{0}{1}?'.format(host, urllib.quote(path.encode('utf8')))

    consumer = oauth2.Consumer(CONSUMER_KEY, CONSUMER_SECRET)
    oauth_request = oauth2.Request(
        method="GET", url=url, parameters=url_params)

    oauth_request.update(
        {
            'oauth_nonce': oauth2.generate_nonce(),
            'oauth_timestamp': oauth2.generate_timestamp(),
            'oauth_token': TOKEN,
            'oauth_consumer_key': CONSUMER_KEY
        }
    )
    token = oauth2.Token(TOKEN, TOKEN_SECRET)
    oauth_request.sign_request(
        oauth2.SignatureMethod_HMAC_SHA1(), consumer, token)
    signed_url = oauth_request.to_url()
    
    
    print u'Querying {0} ...'.format(url)
    
    conn = urllib2.urlopen(signed_url, None)
    try:
        response = json.loads(conn.read())
    finally:
        conn.close()

    return response


def search(term, location, offset, sort, category_filter, deals):
    """Query the Search API by a search term and location.

    Args:
        term (str): The search term passed to the API.
        location (str): The search location passed to the API.

    Returns:
        dict: The JSON response from the request.
    """

    url_params = {
        'term': term.replace(' ', '+'),
        'location': location.replace(' ', '+'),
        'offset': offset,
        'sort': sort,
        'category_filter': category_filter,
        'deals': deals,
        'limit': SEARCH_LIMIT
    }
    """
    print url_params
    """
    return request(API_HOST, SEARCH_PATH, url_params=url_params)


def get_business(business_id):
    """Query the Business API by a business ID.

    Args:
        business_id (str): The ID of the business to query.

    Returns:
        dict: The JSON response from the request.
    """
    business_path = BUSINESS_PATH + business_id

    return request(API_HOST, business_path)


def query_api(term, location, offset, sort, category_filter, deals):
    """Queries the API by the input values from the user.

    Args:
        term (str): The search term to query.
        location (str): The location of the business to query.
    """
    response = search(term, location, offset, sort, category_filter, deals)

    businesses = response.get('businesses')

    if not businesses:
        print u'No businesses for {0} in {1} found.'.format(term, location)
        return

    business_id = businesses[0]['id']

    for business in businesses:
        response = get_business(business['id'])
        pprint.pprint(response)


"""
    old version below.
    for business in businesses:
        response = get_business(business['id'])
        pprint.pprint(response, indent=2)
"""

def main():
    parser = argparse.ArgumentParser()

    parser.add_argument('-q', '--term', dest='term', default=DEFAULT_TERM,
                        type=str, help='Search term (default: %(default)s)')
    parser.add_argument('-l', '--location', dest='location',
                        default=DEFAULT_LOCATION, type=str,
                        help='Search location (default: %(default)s)')

    input_values = parser.parse_args()

    try:
        query_api(input_values.term, input_values.location, DEFAULT_OFFSET, DEFAULT_SORT, DEFAULT_CATEGORY_FILTER, DEFAULT_DEALS_FILTER)
    except urllib2.HTTPError as error:
        sys.exit(
            'Encountered HTTP error {0}. Abort program.'.format(error.code))


if __name__ == '__main__':
    main()
`

**Comment by watterso** [comment]
@bkauyeung this looks like the code sample, I meant more what exactly you are requesting.

**Comment by watterso** [comment]
Furthermore, if you are working in python, are you aware of the [yelp python package](https://github.com/Yelp/yelp-python)? Below is an example of how you can get what you want, although I don't condone my use of `__dict__`, I only used it for illustration purposes.

```
In [15]: params = { 'deals_filter':True}

In [16]: results = client.search('San Francisco', **params)

In [17]: results.businesses[0].deals[0].__dict__
Out[17]:
{'additional_restrictions': u'Promotion lasts for 1 year from date of purchase. After that period, your voucher is redeemable for the amount you paid, less any value you may have received. Not valid with other vouchers, certificates, or offers. Only 1 voucher(s) can be purchased and redeemed per person. Up to 1 can be purchased as gifts for others. Subject to the <a target="_blank" href="http://www.yelp.com/tos/general_b2c_us_20120911">General Terms</a>.',
 'currency_code': u'USD',
 'id': u'gCVnQjTG1GNF6r4wRx4jDg',
 'image_url': u'http://s3-media1.fl.yelpcdn.com/dphoto/QgZP3XYkpZKXZex21UsZdA/m.jpg',
 'important_restriction': None,
 'is_popular': True,
 'options': [<yelp.obj.deal_option.DealOption at 0x104d4f490>],
 'time_end': None,
 'time_start': 1452697246,
 'title': u'$25 for $30',
 'url': u'http://www.yelp.com/deals/elixiria-san-francisco-3?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=7BNvFpVhslu92PlONvXMFQ',
 'what_you_get': u'You get a voucher redeemable for $30 at Elixiria.\nPrint out your voucher, or redeem on your phone with the <a href="http://www.yelp.com/mobile?source=deal_marketing">Yelp app</a>.'}
```

**Comment by bkauyeung** [comment]
I will look at this again. Im a beginner at this stuff, so I will take a bit of time looking at this! Thhanks for your help!!

**Comment by watterso** [comment]
No problem! I'm going to close this issue, feel free to post more questions.
